//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\StringIdConstantsGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DVG.SkyPirates.Shared.Ids
{
    partial struct CactusId
    {
        public static partial class Constants
        {
            public static readonly CactusId Cactus_39_B = new CactusId("Cactus_39_B");
            public static readonly CactusId Cactus_02_B = new CactusId("Cactus_02_B");
            public static readonly CactusId Cactus_03_B = new CactusId("Cactus_03_B");
            public static readonly CactusId Cactus_05_B = new CactusId("Cactus_05_B");
            public static readonly CactusId Cactus_06_B = new CactusId("Cactus_06_B");
            public static readonly CactusId Cactus_07_A = new CactusId("Cactus_07_A");
            public static readonly CactusId Cactus_08_B = new CactusId("Cactus_08_B");
            public static readonly CactusId Cactus_09_A = new CactusId("Cactus_09_A");
            public static readonly CactusId Cactus_10_A = new CactusId("Cactus_10_A");
            public static readonly CactusId Cactus_11_A = new CactusId("Cactus_11_A");
            public static readonly CactusId Cactus_12_A = new CactusId("Cactus_12_A");
            public static readonly CactusId Cactus_13_B = new CactusId("Cactus_13_B");
            public static readonly CactusId Cactus_15_B = new CactusId("Cactus_15_B");
            public static readonly CactusId Cactus_16_A = new CactusId("Cactus_16_A");
            public static readonly CactusId Cactus_18_A = new CactusId("Cactus_18_A");
            public static readonly CactusId Cactus_18_B = new CactusId("Cactus_18_B");
            public static readonly CactusId Cactus_23_B = new CactusId("Cactus_23_B");
            public static readonly CactusId Cactus_25_B = new CactusId("Cactus_25_B");
            public static readonly CactusId Cactus_26_A = new CactusId("Cactus_26_A");
            public static readonly CactusId Cactus_26_B = new CactusId("Cactus_26_B");
            public static readonly CactusId Cactus_30_A = new CactusId("Cactus_30_A");
            public static readonly CactusId Cactus_32_A = new CactusId("Cactus_32_A");
            public static readonly CactusId Cactus_36_A = new CactusId("Cactus_36_A");
            public static readonly CactusId Cactus_37_B = new CactusId("Cactus_37_B");
            public static readonly CactusId Cactus_38_B = new CactusId("Cactus_38_B");
            public static readonly CactusId Cactus_01_A = new CactusId("Cactus_01_A");
            public static readonly CactusId Cactus_01_B = new CactusId("Cactus_01_B");
            public static readonly CactusId Cactus_02_A = new CactusId("Cactus_02_A");
            public static readonly CactusId Cactus_03_A = new CactusId("Cactus_03_A");
            public static readonly CactusId Cactus_04_A = new CactusId("Cactus_04_A");
            public static readonly CactusId Cactus_04_B = new CactusId("Cactus_04_B");
            public static readonly CactusId Cactus_05_A = new CactusId("Cactus_05_A");
            public static readonly CactusId Cactus_06_A = new CactusId("Cactus_06_A");
            public static readonly CactusId Cactus_07_B = new CactusId("Cactus_07_B");
            public static readonly CactusId Cactus_08_A = new CactusId("Cactus_08_A");
            public static readonly CactusId Cactus_09_B = new CactusId("Cactus_09_B");
            public static readonly CactusId Cactus_10_B = new CactusId("Cactus_10_B");
            public static readonly CactusId Cactus_11_B = new CactusId("Cactus_11_B");
            public static readonly CactusId Cactus_12_B = new CactusId("Cactus_12_B");
            public static readonly CactusId Cactus_13_A = new CactusId("Cactus_13_A");
            public static readonly CactusId Cactus_14_A = new CactusId("Cactus_14_A");
            public static readonly CactusId Cactus_14_B = new CactusId("Cactus_14_B");
            public static readonly CactusId Cactus_15_A = new CactusId("Cactus_15_A");
            public static readonly CactusId Cactus_16_B = new CactusId("Cactus_16_B");
            public static readonly CactusId Cactus_17_A = new CactusId("Cactus_17_A");
            public static readonly CactusId Cactus_17_B = new CactusId("Cactus_17_B");
            public static readonly CactusId Cactus_19_A = new CactusId("Cactus_19_A");
            public static readonly CactusId Cactus_19_B = new CactusId("Cactus_19_B");
            public static readonly CactusId Cactus_20_A = new CactusId("Cactus_20_A");
            public static readonly CactusId Cactus_20_B = new CactusId("Cactus_20_B");
            public static readonly CactusId Cactus_21_A = new CactusId("Cactus_21_A");
            public static readonly CactusId Cactus_21_B = new CactusId("Cactus_21_B");
            public static readonly CactusId Cactus_22_A = new CactusId("Cactus_22_A");
            public static readonly CactusId Cactus_22_B = new CactusId("Cactus_22_B");
            public static readonly CactusId Cactus_23_A = new CactusId("Cactus_23_A");
            public static readonly CactusId Cactus_24_A = new CactusId("Cactus_24_A");
            public static readonly CactusId Cactus_24_B = new CactusId("Cactus_24_B");
            public static readonly CactusId Cactus_25_A = new CactusId("Cactus_25_A");
            public static readonly CactusId Cactus_27_A = new CactusId("Cactus_27_A");
            public static readonly CactusId Cactus_27_B = new CactusId("Cactus_27_B");
            public static readonly CactusId Cactus_28_A = new CactusId("Cactus_28_A");
            public static readonly CactusId Cactus_28_B = new CactusId("Cactus_28_B");
            public static readonly CactusId Cactus_29_A = new CactusId("Cactus_29_A");
            public static readonly CactusId Cactus_29_B = new CactusId("Cactus_29_B");
            public static readonly CactusId Cactus_30_B = new CactusId("Cactus_30_B");
            public static readonly CactusId Cactus_31_A = new CactusId("Cactus_31_A");
            public static readonly CactusId Cactus_31_B = new CactusId("Cactus_31_B");
            public static readonly CactusId Cactus_32_B = new CactusId("Cactus_32_B");
            public static readonly CactusId Cactus_33_A = new CactusId("Cactus_33_A");
            public static readonly CactusId Cactus_33_B = new CactusId("Cactus_33_B");
            public static readonly CactusId Cactus_34_A = new CactusId("Cactus_34_A");
            public static readonly CactusId Cactus_34_B = new CactusId("Cactus_34_B");
            public static readonly CactusId Cactus_35_A = new CactusId("Cactus_35_A");
            public static readonly CactusId Cactus_35_B = new CactusId("Cactus_35_B");
            public static readonly CactusId Cactus_36_B = new CactusId("Cactus_36_B");
            public static readonly CactusId Cactus_37_A = new CactusId("Cactus_37_A");
            public static readonly CactusId Cactus_38_A = new CactusId("Cactus_38_A");
            public static readonly CactusId Cactus_39_A = new CactusId("Cactus_39_A");

            private static readonly CactusId[] _allIds = new CactusId[]
            {
                new CactusId("Cactus_39_B"),
                new CactusId("Cactus_02_B"),
                new CactusId("Cactus_03_B"),
                new CactusId("Cactus_05_B"),
                new CactusId("Cactus_06_B"),
                new CactusId("Cactus_07_A"),
                new CactusId("Cactus_08_B"),
                new CactusId("Cactus_09_A"),
                new CactusId("Cactus_10_A"),
                new CactusId("Cactus_11_A"),
                new CactusId("Cactus_12_A"),
                new CactusId("Cactus_13_B"),
                new CactusId("Cactus_15_B"),
                new CactusId("Cactus_16_A"),
                new CactusId("Cactus_18_A"),
                new CactusId("Cactus_18_B"),
                new CactusId("Cactus_23_B"),
                new CactusId("Cactus_25_B"),
                new CactusId("Cactus_26_A"),
                new CactusId("Cactus_26_B"),
                new CactusId("Cactus_30_A"),
                new CactusId("Cactus_32_A"),
                new CactusId("Cactus_36_A"),
                new CactusId("Cactus_37_B"),
                new CactusId("Cactus_38_B"),
                new CactusId("Cactus_01_A"),
                new CactusId("Cactus_01_B"),
                new CactusId("Cactus_02_A"),
                new CactusId("Cactus_03_A"),
                new CactusId("Cactus_04_A"),
                new CactusId("Cactus_04_B"),
                new CactusId("Cactus_05_A"),
                new CactusId("Cactus_06_A"),
                new CactusId("Cactus_07_B"),
                new CactusId("Cactus_08_A"),
                new CactusId("Cactus_09_B"),
                new CactusId("Cactus_10_B"),
                new CactusId("Cactus_11_B"),
                new CactusId("Cactus_12_B"),
                new CactusId("Cactus_13_A"),
                new CactusId("Cactus_14_A"),
                new CactusId("Cactus_14_B"),
                new CactusId("Cactus_15_A"),
                new CactusId("Cactus_16_B"),
                new CactusId("Cactus_17_A"),
                new CactusId("Cactus_17_B"),
                new CactusId("Cactus_19_A"),
                new CactusId("Cactus_19_B"),
                new CactusId("Cactus_20_A"),
                new CactusId("Cactus_20_B"),
                new CactusId("Cactus_21_A"),
                new CactusId("Cactus_21_B"),
                new CactusId("Cactus_22_A"),
                new CactusId("Cactus_22_B"),
                new CactusId("Cactus_23_A"),
                new CactusId("Cactus_24_A"),
                new CactusId("Cactus_24_B"),
                new CactusId("Cactus_25_A"),
                new CactusId("Cactus_27_A"),
                new CactusId("Cactus_27_B"),
                new CactusId("Cactus_28_A"),
                new CactusId("Cactus_28_B"),
                new CactusId("Cactus_29_A"),
                new CactusId("Cactus_29_B"),
                new CactusId("Cactus_30_B"),
                new CactusId("Cactus_31_A"),
                new CactusId("Cactus_31_B"),
                new CactusId("Cactus_32_B"),
                new CactusId("Cactus_33_A"),
                new CactusId("Cactus_33_B"),
                new CactusId("Cactus_34_A"),
                new CactusId("Cactus_34_B"),
                new CactusId("Cactus_35_A"),
                new CactusId("Cactus_35_B"),
                new CactusId("Cactus_36_B"),
                new CactusId("Cactus_37_A"),
                new CactusId("Cactus_38_A"),
                new CactusId("Cactus_39_A"),
            };
            public static ReadOnlySpan<CactusId> AllIds => _allIds;
        }
    }
}
