//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\CommandGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using DVG.SkyPirates.Shared.Commands;

namespace DVG.Commands
{
    public static class CommandIds
    {
        private static readonly Dictionary<Type, int> _typeToId;
        private static readonly Dictionary<int, Type> _idToType;

        static CommandIds()
        {
            _typeToId = new Dictionary<Type, int>()
            {
                {typeof(JoystickCommand), 1},
                {typeof(LoadWorldCommand), 2},
                {typeof(SpawnSquadCommand), 3},
                {typeof(SpawnUnitCommand), 4},
                {typeof(TickSyncCommand), 5},
            };
            
            _idToType = new Dictionary<int, Type>()
            {
                {1, typeof(JoystickCommand)},
                {2, typeof(LoadWorldCommand)},
                {3, typeof(SpawnSquadCommand)},
                {4, typeof(SpawnUnitCommand)},
                {5, typeof(TickSyncCommand)},
            };
        }

        
        public static void ForEachData<T>(ref T action)
            where T: IGenericAction<ICommandData>
        {
            action.Invoke<JoystickCommand>();
            action.Invoke<LoadWorldCommand>();
            action.Invoke<SpawnSquadCommand>();
            action.Invoke<SpawnUnitCommand>();
            action.Invoke<TickSyncCommand>();
        }

        public static int GetId<T>() => _typeToId[typeof(T)];
        public static Type GetCommand(ushort id) => _idToType[id];
    }
}

