//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\CommandGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using DVG.SkyPirates.Shared.Commands;

namespace DVG.Core.Commands
{
    public static class CommandIds
    {
        private static readonly Dictionary<Type, int> _typeToId;
        private static readonly Dictionary<int, Type> _idToType;

        static CommandIds()
        {
            _typeToId = new Dictionary<Type, int>()
            {
                {typeof(DirectionCommand), 1},
                {typeof(FixationCommand), 2},
                {typeof(ConnectionCommand), 3},
                {typeof(SpawnSquadCommand), 4},
                {typeof(SpawnUnitCommand), 5},
                {typeof(StartGameCommand), 6},
            };
            
            _idToType = new Dictionary<int, Type>()
            {
                {1, typeof(DirectionCommand)},
                {2, typeof(FixationCommand)},
                {3, typeof(ConnectionCommand)},
                {4, typeof(SpawnSquadCommand)},
                {5, typeof(SpawnUnitCommand)},
                {6, typeof(StartGameCommand)},
            };
        }

        
        public static void ForEachData<T>(ref T action)
            where T: IGenericAction<ICommandData>
        {
            action.Invoke<DirectionCommand>();
            action.Invoke<FixationCommand>();
            action.Invoke<ConnectionCommand>();
            action.Invoke<SpawnSquadCommand>();
            action.Invoke<SpawnUnitCommand>();
            action.Invoke<StartGameCommand>();
        }

        public static int GetId<T>() => _typeToId[typeof(T)];
        public static Type GetCommand(ushort id) => _idToType[id];
    }
}

