//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\CommandDataGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using DVG.Commands;

using DVG.SkyPirates.Shared.Commands;

namespace DVG.SkyPirates.Shared.Commands
{
    public sealed class CommandsData
    {

        public Dictionary<int, List<Command<InvalidateCommand>>> InvalidateCommand;
        public Dictionary<int, List<Command<JoystickCommand>>> JoystickCommand;
        public Dictionary<int, List<Command<LoadWorldCommand>>> LoadWorldCommand;
        public Dictionary<int, List<Command<SpawnSquadCommand>>> SpawnSquadCommand;
        public Dictionary<int, List<Command<SpawnUnitCommand>>> SpawnUnitCommand;
        public Dictionary<int, List<Command<TickSyncCommand>>> TickSyncCommand;

        public CommandsData()
        {

            InvalidateCommand = new();
            JoystickCommand = new();
            LoadWorldCommand = new();
            SpawnSquadCommand = new();
            SpawnUnitCommand = new();
            TickSyncCommand = new();
        }

        public Dictionary<int, List<Command<T>>> Get<T>()
        {

            if (typeof(T) == typeof(InvalidateCommand))
                return InvalidateCommand as Dictionary<int, List<Command<T>>>;
            if (typeof(T) == typeof(JoystickCommand))
                return JoystickCommand as Dictionary<int, List<Command<T>>>;
            if (typeof(T) == typeof(LoadWorldCommand))
                return LoadWorldCommand as Dictionary<int, List<Command<T>>>;
            if (typeof(T) == typeof(SpawnSquadCommand))
                return SpawnSquadCommand as Dictionary<int, List<Command<T>>>;
            if (typeof(T) == typeof(SpawnUnitCommand))
                return SpawnUnitCommand as Dictionary<int, List<Command<T>>>;
            if (typeof(T) == typeof(TickSyncCommand))
                return TickSyncCommand as Dictionary<int, List<Command<T>>>;

            throw new NotSupportedException(typeof(T).Name);
        }

        public void Set<T>(Dictionary<int, List<Command<T>>> data)
        {

            if (typeof(T) == typeof(InvalidateCommand))
            {
                InvalidateCommand = data as Dictionary<int, List<Command<InvalidateCommand>>>;
                return;
            }
            if (typeof(T) == typeof(JoystickCommand))
            {
                JoystickCommand = data as Dictionary<int, List<Command<JoystickCommand>>>;
                return;
            }
            if (typeof(T) == typeof(LoadWorldCommand))
            {
                LoadWorldCommand = data as Dictionary<int, List<Command<LoadWorldCommand>>>;
                return;
            }
            if (typeof(T) == typeof(SpawnSquadCommand))
            {
                SpawnSquadCommand = data as Dictionary<int, List<Command<SpawnSquadCommand>>>;
                return;
            }
            if (typeof(T) == typeof(SpawnUnitCommand))
            {
                SpawnUnitCommand = data as Dictionary<int, List<Command<SpawnUnitCommand>>>;
                return;
            }
            if (typeof(T) == typeof(TickSyncCommand))
            {
                TickSyncCommand = data as Dictionary<int, List<Command<TickSyncCommand>>>;
                return;
            }

            throw new NotSupportedException(typeof(T).Name);
        }
    }
}
