//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\CommandsRegistryGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using DVG.SkyPirates.Shared.Commands;

namespace DVG.Commands
{
    public static class CommandsRegistry
    {        
        public static void ForEach<T>(ref T action)
            where T: IGenericAction
        {
            action.Invoke<InvalidateCommand>();
            action.Invoke<JoystickCommand>();
            action.Invoke<LoadWorldCommand>();
            action.Invoke<SpawnSquadCommand>();
            action.Invoke<SpawnUnitCommand>();
            action.Invoke<TickSyncCommand>();
        }

        public static int GetId<T>()
        {
            Type type = typeof(T);

            if (type == typeof(InvalidateCommand))
                return 1;
            if (type == typeof(JoystickCommand))
                return 2;
            if (type == typeof(LoadWorldCommand))
                return 3;
            if (type == typeof(SpawnSquadCommand))
                return 4;
            if (type == typeof(SpawnUnitCommand))
                return 5;
            if (type == typeof(TickSyncCommand))
                return 6;

            throw new NotSupportedException(type.Name);
        }

        public static bool IsPredicted<T>()
        {
            Type type = typeof(T);

            if(type == typeof(InvalidateCommand))
                return false;
            if(type == typeof(JoystickCommand))
                return true;
            if(type == typeof(LoadWorldCommand))
                return false;
            if(type == typeof(SpawnSquadCommand))
                return false;
            if(type == typeof(SpawnUnitCommand))
                return false;
            if(type == typeof(TickSyncCommand))
                return false;

            throw new NotSupportedException(type.Name);
        }

        public static void Call<T>(int id, ref T action)
            where T : IGenericAction
        {
            if(id == 1)
                action.Invoke<InvalidateCommand>();
            if(id == 2)
                action.Invoke<JoystickCommand>();
            if(id == 3)
                action.Invoke<LoadWorldCommand>();
            if(id == 4)
                action.Invoke<SpawnSquadCommand>();
            if(id == 5)
                action.Invoke<SpawnUnitCommand>();
            if(id == 6)
                action.Invoke<TickSyncCommand>();
        }
    }
}
