//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\ComponentGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using DVG.SkyPirates.Shared.Components;
using DVG.SkyPirates.Shared.Ids;
using DVG.SkyPirates.Shared.Components.Config;

namespace DVG.Core.Components
{
    public static class ComponentIds
    {
        private static readonly Dictionary<Type, int> _typeToId;
        private static readonly Dictionary<int, Type> _idToType;

        static ComponentIds()
        {
            _typeToId = new Dictionary<Type, int>()
            {
                {typeof(Alive), 1},
                {typeof(AutoHeal), 2},
                {typeof(BehaviourConfig), 3},
                {typeof(BehaviourState), 4},
                {typeof(CachePosition), 5},
                {typeof(CactusId), 6},
                {typeof(Damage), 7},
                {typeof(Destination), 8},
                {typeof(Direction), 9},
                {typeof(Fixation), 10},
                {typeof(Health), 11},
                {typeof(HexMap), 12},
                {typeof(ImpactDistance), 13},
                {typeof(Level), 14},
                {typeof(MaxHealth), 15},
                {typeof(MaxSpeed), 16},
                {typeof(Position), 17},
                {typeof(Radius), 18},
                {typeof(RecivedDamage), 19},
                {typeof(RockId), 20},
                {typeof(Rotation), 21},
                {typeof(Separation), 22},
                {typeof(SeparationForce), 23},
                {typeof(Squad), 24},
                {typeof(Target), 25},
                {typeof(Targets), 26},
                {typeof(TargetSearchData), 27},
                {typeof(Team), 28},
                {typeof(TreeId), 29},
                {typeof(UnitId), 30},
            };
            
            _idToType = new Dictionary<int, Type>()
            {
                {1, typeof(Alive)},
                {2, typeof(AutoHeal)},
                {3, typeof(BehaviourConfig)},
                {4, typeof(BehaviourState)},
                {5, typeof(CachePosition)},
                {6, typeof(CactusId)},
                {7, typeof(Damage)},
                {8, typeof(Destination)},
                {9, typeof(Direction)},
                {10, typeof(Fixation)},
                {11, typeof(Health)},
                {12, typeof(HexMap)},
                {13, typeof(ImpactDistance)},
                {14, typeof(Level)},
                {15, typeof(MaxHealth)},
                {16, typeof(MaxSpeed)},
                {17, typeof(Position)},
                {18, typeof(Radius)},
                {19, typeof(RecivedDamage)},
                {20, typeof(RockId)},
                {21, typeof(Rotation)},
                {22, typeof(Separation)},
                {23, typeof(SeparationForce)},
                {24, typeof(Squad)},
                {25, typeof(Target)},
                {26, typeof(Targets)},
                {27, typeof(TargetSearchData)},
                {28, typeof(Team)},
                {29, typeof(TreeId)},
                {30, typeof(UnitId)},
            };
        }

        
        public static void ForEachData<T>(ref T action)
            where T: IStructGenericAction
        {
            action.Invoke<Alive>();
            action.Invoke<AutoHeal>();
            action.Invoke<BehaviourConfig>();
            action.Invoke<BehaviourState>();
            action.Invoke<CachePosition>();
            action.Invoke<CactusId>();
            action.Invoke<Damage>();
            action.Invoke<Destination>();
            action.Invoke<Direction>();
            action.Invoke<Fixation>();
            action.Invoke<Health>();
            action.Invoke<HexMap>();
            action.Invoke<ImpactDistance>();
            action.Invoke<Level>();
            action.Invoke<MaxHealth>();
            action.Invoke<MaxSpeed>();
            action.Invoke<Position>();
            action.Invoke<Radius>();
            action.Invoke<RecivedDamage>();
            action.Invoke<RockId>();
            action.Invoke<Rotation>();
            action.Invoke<Separation>();
            action.Invoke<SeparationForce>();
            action.Invoke<Squad>();
            action.Invoke<Target>();
            action.Invoke<Targets>();
            action.Invoke<TargetSearchData>();
            action.Invoke<Team>();
            action.Invoke<TreeId>();
            action.Invoke<UnitId>();
        }
    }
}

