//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\ComponentsDataGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using System.Runtime.CompilerServices;

using DVG.SkyPirates.Shared.Components.Runtime;
using DVG.SkyPirates.Shared.Components.Config;
using DVG.SkyPirates.Shared.Components.Framed;
using DVG.SkyPirates.Shared.Ids;
using DVG.Components;

namespace DVG.SkyPirates.Shared.Data
{
    [Serializable]
    [DataContract]
    public sealed class ComponentsData: IStructGenericCaller
    {

        [DataMember(Order = 0)]
        private AutoHeal? AutoHeal;
        [DataMember(Order = 1)]
        private BehaviourConfig? BehaviourConfig;
        [DataMember(Order = 2)]
        private BehaviourState? BehaviourState;
        [DataMember(Order = 3)]
        private CachePosition? CachePosition;
        [DataMember(Order = 4)]
        private CactusId? CactusId;
        [DataMember(Order = 5)]
        private ClientId? ClientId;
        [DataMember(Order = 6)]
        private Collide? Collide;
        [DataMember(Order = 7)]
        private Damage? Damage;
        [DataMember(Order = 8)]
        private Destination? Destination;
        [DataMember(Order = 9)]
        private Direction? Direction;
        [DataMember(Order = 10)]
        private Disposing? Disposing;
        [DataMember(Order = 11)]
        private Fixation? Fixation;
        [DataMember(Order = 12)]
        private FlyDestination? FlyDestination;
        [DataMember(Order = 13)]
        private GoodsAmount? GoodsAmount;
        [DataMember(Order = 14)]
        private GoodsCollectorRadius? GoodsCollectorRadius;
        [DataMember(Order = 15)]
        private GoodsDrop? GoodsDrop;
        [DataMember(Order = 16)]
        private GoodsId? GoodsId;
        [DataMember(Order = 17)]
        private Health? Health;
        [DataMember(Order = 18)]
        private HexMap? HexMap;
        [DataMember(Order = 19)]
        private ImpactDistance? ImpactDistance;
        [DataMember(Order = 20)]
        private Level? Level;
        [DataMember(Order = 21)]
        private MaxHealth? MaxHealth;
        [DataMember(Order = 22)]
        private MaxSpeed? MaxSpeed;
        [DataMember(Order = 23)]
        private Position? Position;
        [DataMember(Order = 24)]
        private Radius? Radius;
        [DataMember(Order = 25)]
        private RandomSeed? RandomSeed;
        [DataMember(Order = 26)]
        private RecivedDamage? RecivedDamage;
        [DataMember(Order = 27)]
        private RockId? RockId;
        [DataMember(Order = 28)]
        private Rotation? Rotation;
        [DataMember(Order = 29)]
        private Separation? Separation;
        [DataMember(Order = 30)]
        private Separator? Separator;
        [DataMember(Order = 31)]
        private Squad? Squad;
        [DataMember(Order = 32)]
        private SquadMember? SquadMember;
        [DataMember(Order = 33)]
        private SquadMemberCount? SquadMemberCount;
        [DataMember(Order = 34)]
        private SyncId? SyncId;
        [DataMember(Order = 35)]
        private SyncIdReserve? SyncIdReserve;
        [DataMember(Order = 36)]
        private Target? Target;
        [DataMember(Order = 37)]
        private Targets? Targets;
        [DataMember(Order = 38)]
        private TargetSearchDistance? TargetSearchDistance;
        [DataMember(Order = 39)]
        private TargetSearchPosition? TargetSearchPosition;
        [DataMember(Order = 40)]
        private TeamId? TeamId;
        [DataMember(Order = 41)]
        private TreeId? TreeId;
        [DataMember(Order = 42)]
        private UnitId? UnitId;

        public T? Get<T>()
            where T : struct
        {
            Type type = typeof(T);

            if (type == typeof(AutoHeal))
                return Unsafe.As<AutoHeal?, T?>(ref AutoHeal);
            if (type == typeof(BehaviourConfig))
                return Unsafe.As<BehaviourConfig?, T?>(ref BehaviourConfig);
            if (type == typeof(BehaviourState))
                return Unsafe.As<BehaviourState?, T?>(ref BehaviourState);
            if (type == typeof(CachePosition))
                return Unsafe.As<CachePosition?, T?>(ref CachePosition);
            if (type == typeof(CactusId))
                return Unsafe.As<CactusId?, T?>(ref CactusId);
            if (type == typeof(ClientId))
                return Unsafe.As<ClientId?, T?>(ref ClientId);
            if (type == typeof(Collide))
                return Unsafe.As<Collide?, T?>(ref Collide);
            if (type == typeof(Damage))
                return Unsafe.As<Damage?, T?>(ref Damage);
            if (type == typeof(Destination))
                return Unsafe.As<Destination?, T?>(ref Destination);
            if (type == typeof(Direction))
                return Unsafe.As<Direction?, T?>(ref Direction);
            if (type == typeof(Disposing))
                return Unsafe.As<Disposing?, T?>(ref Disposing);
            if (type == typeof(Fixation))
                return Unsafe.As<Fixation?, T?>(ref Fixation);
            if (type == typeof(FlyDestination))
                return Unsafe.As<FlyDestination?, T?>(ref FlyDestination);
            if (type == typeof(GoodsAmount))
                return Unsafe.As<GoodsAmount?, T?>(ref GoodsAmount);
            if (type == typeof(GoodsCollectorRadius))
                return Unsafe.As<GoodsCollectorRadius?, T?>(ref GoodsCollectorRadius);
            if (type == typeof(GoodsDrop))
                return Unsafe.As<GoodsDrop?, T?>(ref GoodsDrop);
            if (type == typeof(GoodsId))
                return Unsafe.As<GoodsId?, T?>(ref GoodsId);
            if (type == typeof(Health))
                return Unsafe.As<Health?, T?>(ref Health);
            if (type == typeof(HexMap))
                return Unsafe.As<HexMap?, T?>(ref HexMap);
            if (type == typeof(ImpactDistance))
                return Unsafe.As<ImpactDistance?, T?>(ref ImpactDistance);
            if (type == typeof(Level))
                return Unsafe.As<Level?, T?>(ref Level);
            if (type == typeof(MaxHealth))
                return Unsafe.As<MaxHealth?, T?>(ref MaxHealth);
            if (type == typeof(MaxSpeed))
                return Unsafe.As<MaxSpeed?, T?>(ref MaxSpeed);
            if (type == typeof(Position))
                return Unsafe.As<Position?, T?>(ref Position);
            if (type == typeof(Radius))
                return Unsafe.As<Radius?, T?>(ref Radius);
            if (type == typeof(RandomSeed))
                return Unsafe.As<RandomSeed?, T?>(ref RandomSeed);
            if (type == typeof(RecivedDamage))
                return Unsafe.As<RecivedDamage?, T?>(ref RecivedDamage);
            if (type == typeof(RockId))
                return Unsafe.As<RockId?, T?>(ref RockId);
            if (type == typeof(Rotation))
                return Unsafe.As<Rotation?, T?>(ref Rotation);
            if (type == typeof(Separation))
                return Unsafe.As<Separation?, T?>(ref Separation);
            if (type == typeof(Separator))
                return Unsafe.As<Separator?, T?>(ref Separator);
            if (type == typeof(Squad))
                return Unsafe.As<Squad?, T?>(ref Squad);
            if (type == typeof(SquadMember))
                return Unsafe.As<SquadMember?, T?>(ref SquadMember);
            if (type == typeof(SquadMemberCount))
                return Unsafe.As<SquadMemberCount?, T?>(ref SquadMemberCount);
            if (type == typeof(SyncId))
                return Unsafe.As<SyncId?, T?>(ref SyncId);
            if (type == typeof(SyncIdReserve))
                return Unsafe.As<SyncIdReserve?, T?>(ref SyncIdReserve);
            if (type == typeof(Target))
                return Unsafe.As<Target?, T?>(ref Target);
            if (type == typeof(Targets))
                return Unsafe.As<Targets?, T?>(ref Targets);
            if (type == typeof(TargetSearchDistance))
                return Unsafe.As<TargetSearchDistance?, T?>(ref TargetSearchDistance);
            if (type == typeof(TargetSearchPosition))
                return Unsafe.As<TargetSearchPosition?, T?>(ref TargetSearchPosition);
            if (type == typeof(TeamId))
                return Unsafe.As<TeamId?, T?>(ref TeamId);
            if (type == typeof(TreeId))
                return Unsafe.As<TreeId?, T?>(ref TreeId);
            if (type == typeof(UnitId))
                return Unsafe.As<UnitId?, T?>(ref UnitId);

            throw new NotSupportedException(type.Name);
        }

        public void Set<T>(T? data)
            where T : struct
        {
            Type type = typeof(T);

            if (type == typeof(AutoHeal))
            {
                AutoHeal = Unsafe.As<T?, AutoHeal?>(ref data);
                return;
            }
            if (type == typeof(BehaviourConfig))
            {
                BehaviourConfig = Unsafe.As<T?, BehaviourConfig?>(ref data);
                return;
            }
            if (type == typeof(BehaviourState))
            {
                BehaviourState = Unsafe.As<T?, BehaviourState?>(ref data);
                return;
            }
            if (type == typeof(CachePosition))
            {
                CachePosition = Unsafe.As<T?, CachePosition?>(ref data);
                return;
            }
            if (type == typeof(CactusId))
            {
                CactusId = Unsafe.As<T?, CactusId?>(ref data);
                return;
            }
            if (type == typeof(ClientId))
            {
                ClientId = Unsafe.As<T?, ClientId?>(ref data);
                return;
            }
            if (type == typeof(Collide))
            {
                Collide = Unsafe.As<T?, Collide?>(ref data);
                return;
            }
            if (type == typeof(Damage))
            {
                Damage = Unsafe.As<T?, Damage?>(ref data);
                return;
            }
            if (type == typeof(Destination))
            {
                Destination = Unsafe.As<T?, Destination?>(ref data);
                return;
            }
            if (type == typeof(Direction))
            {
                Direction = Unsafe.As<T?, Direction?>(ref data);
                return;
            }
            if (type == typeof(Disposing))
            {
                Disposing = Unsafe.As<T?, Disposing?>(ref data);
                return;
            }
            if (type == typeof(Fixation))
            {
                Fixation = Unsafe.As<T?, Fixation?>(ref data);
                return;
            }
            if (type == typeof(FlyDestination))
            {
                FlyDestination = Unsafe.As<T?, FlyDestination?>(ref data);
                return;
            }
            if (type == typeof(GoodsAmount))
            {
                GoodsAmount = Unsafe.As<T?, GoodsAmount?>(ref data);
                return;
            }
            if (type == typeof(GoodsCollectorRadius))
            {
                GoodsCollectorRadius = Unsafe.As<T?, GoodsCollectorRadius?>(ref data);
                return;
            }
            if (type == typeof(GoodsDrop))
            {
                GoodsDrop = Unsafe.As<T?, GoodsDrop?>(ref data);
                return;
            }
            if (type == typeof(GoodsId))
            {
                GoodsId = Unsafe.As<T?, GoodsId?>(ref data);
                return;
            }
            if (type == typeof(Health))
            {
                Health = Unsafe.As<T?, Health?>(ref data);
                return;
            }
            if (type == typeof(HexMap))
            {
                HexMap = Unsafe.As<T?, HexMap?>(ref data);
                return;
            }
            if (type == typeof(ImpactDistance))
            {
                ImpactDistance = Unsafe.As<T?, ImpactDistance?>(ref data);
                return;
            }
            if (type == typeof(Level))
            {
                Level = Unsafe.As<T?, Level?>(ref data);
                return;
            }
            if (type == typeof(MaxHealth))
            {
                MaxHealth = Unsafe.As<T?, MaxHealth?>(ref data);
                return;
            }
            if (type == typeof(MaxSpeed))
            {
                MaxSpeed = Unsafe.As<T?, MaxSpeed?>(ref data);
                return;
            }
            if (type == typeof(Position))
            {
                Position = Unsafe.As<T?, Position?>(ref data);
                return;
            }
            if (type == typeof(Radius))
            {
                Radius = Unsafe.As<T?, Radius?>(ref data);
                return;
            }
            if (type == typeof(RandomSeed))
            {
                RandomSeed = Unsafe.As<T?, RandomSeed?>(ref data);
                return;
            }
            if (type == typeof(RecivedDamage))
            {
                RecivedDamage = Unsafe.As<T?, RecivedDamage?>(ref data);
                return;
            }
            if (type == typeof(RockId))
            {
                RockId = Unsafe.As<T?, RockId?>(ref data);
                return;
            }
            if (type == typeof(Rotation))
            {
                Rotation = Unsafe.As<T?, Rotation?>(ref data);
                return;
            }
            if (type == typeof(Separation))
            {
                Separation = Unsafe.As<T?, Separation?>(ref data);
                return;
            }
            if (type == typeof(Separator))
            {
                Separator = Unsafe.As<T?, Separator?>(ref data);
                return;
            }
            if (type == typeof(Squad))
            {
                Squad = Unsafe.As<T?, Squad?>(ref data);
                return;
            }
            if (type == typeof(SquadMember))
            {
                SquadMember = Unsafe.As<T?, SquadMember?>(ref data);
                return;
            }
            if (type == typeof(SquadMemberCount))
            {
                SquadMemberCount = Unsafe.As<T?, SquadMemberCount?>(ref data);
                return;
            }
            if (type == typeof(SyncId))
            {
                SyncId = Unsafe.As<T?, SyncId?>(ref data);
                return;
            }
            if (type == typeof(SyncIdReserve))
            {
                SyncIdReserve = Unsafe.As<T?, SyncIdReserve?>(ref data);
                return;
            }
            if (type == typeof(Target))
            {
                Target = Unsafe.As<T?, Target?>(ref data);
                return;
            }
            if (type == typeof(Targets))
            {
                Targets = Unsafe.As<T?, Targets?>(ref data);
                return;
            }
            if (type == typeof(TargetSearchDistance))
            {
                TargetSearchDistance = Unsafe.As<T?, TargetSearchDistance?>(ref data);
                return;
            }
            if (type == typeof(TargetSearchPosition))
            {
                TargetSearchPosition = Unsafe.As<T?, TargetSearchPosition?>(ref data);
                return;
            }
            if (type == typeof(TeamId))
            {
                TeamId = Unsafe.As<T?, TeamId?>(ref data);
                return;
            }
            if (type == typeof(TreeId))
            {
                TreeId = Unsafe.As<T?, TreeId?>(ref data);
                return;
            }
            if (type == typeof(UnitId))
            {
                UnitId = Unsafe.As<T?, UnitId?>(ref data);
                return;
            }

            throw new NotSupportedException(type.Name);
        }

        public Type[] GetTypes()
        {
            int typesCount = 

                (AutoHeal.HasValue? 1 : 0) + 
                (BehaviourConfig.HasValue? 1 : 0) + 
                (BehaviourState.HasValue? 1 : 0) + 
                (CachePosition.HasValue? 1 : 0) + 
                (CactusId.HasValue? 1 : 0) + 
                (ClientId.HasValue? 1 : 0) + 
                (Collide.HasValue? 1 : 0) + 
                (Damage.HasValue? 1 : 0) + 
                (Destination.HasValue? 1 : 0) + 
                (Direction.HasValue? 1 : 0) + 
                (Disposing.HasValue? 1 : 0) + 
                (Fixation.HasValue? 1 : 0) + 
                (FlyDestination.HasValue? 1 : 0) + 
                (GoodsAmount.HasValue? 1 : 0) + 
                (GoodsCollectorRadius.HasValue? 1 : 0) + 
                (GoodsDrop.HasValue? 1 : 0) + 
                (GoodsId.HasValue? 1 : 0) + 
                (Health.HasValue? 1 : 0) + 
                (HexMap.HasValue? 1 : 0) + 
                (ImpactDistance.HasValue? 1 : 0) + 
                (Level.HasValue? 1 : 0) + 
                (MaxHealth.HasValue? 1 : 0) + 
                (MaxSpeed.HasValue? 1 : 0) + 
                (Position.HasValue? 1 : 0) + 
                (Radius.HasValue? 1 : 0) + 
                (RandomSeed.HasValue? 1 : 0) + 
                (RecivedDamage.HasValue? 1 : 0) + 
                (RockId.HasValue? 1 : 0) + 
                (Rotation.HasValue? 1 : 0) + 
                (Separation.HasValue? 1 : 0) + 
                (Separator.HasValue? 1 : 0) + 
                (Squad.HasValue? 1 : 0) + 
                (SquadMember.HasValue? 1 : 0) + 
                (SquadMemberCount.HasValue? 1 : 0) + 
                (SyncId.HasValue? 1 : 0) + 
                (SyncIdReserve.HasValue? 1 : 0) + 
                (Target.HasValue? 1 : 0) + 
                (Targets.HasValue? 1 : 0) + 
                (TargetSearchDistance.HasValue? 1 : 0) + 
                (TargetSearchPosition.HasValue? 1 : 0) + 
                (TeamId.HasValue? 1 : 0) + 
                (TreeId.HasValue? 1 : 0) + 
                (UnitId.HasValue? 1 : 0);
            
            Type[] types = new Type[typesCount];
            int i = 0;


            if(AutoHeal.HasValue)
                types[i++] = typeof(AutoHeal);
            if(BehaviourConfig.HasValue)
                types[i++] = typeof(BehaviourConfig);
            if(BehaviourState.HasValue)
                types[i++] = typeof(BehaviourState);
            if(CachePosition.HasValue)
                types[i++] = typeof(CachePosition);
            if(CactusId.HasValue)
                types[i++] = typeof(CactusId);
            if(ClientId.HasValue)
                types[i++] = typeof(ClientId);
            if(Collide.HasValue)
                types[i++] = typeof(Collide);
            if(Damage.HasValue)
                types[i++] = typeof(Damage);
            if(Destination.HasValue)
                types[i++] = typeof(Destination);
            if(Direction.HasValue)
                types[i++] = typeof(Direction);
            if(Disposing.HasValue)
                types[i++] = typeof(Disposing);
            if(Fixation.HasValue)
                types[i++] = typeof(Fixation);
            if(FlyDestination.HasValue)
                types[i++] = typeof(FlyDestination);
            if(GoodsAmount.HasValue)
                types[i++] = typeof(GoodsAmount);
            if(GoodsCollectorRadius.HasValue)
                types[i++] = typeof(GoodsCollectorRadius);
            if(GoodsDrop.HasValue)
                types[i++] = typeof(GoodsDrop);
            if(GoodsId.HasValue)
                types[i++] = typeof(GoodsId);
            if(Health.HasValue)
                types[i++] = typeof(Health);
            if(HexMap.HasValue)
                types[i++] = typeof(HexMap);
            if(ImpactDistance.HasValue)
                types[i++] = typeof(ImpactDistance);
            if(Level.HasValue)
                types[i++] = typeof(Level);
            if(MaxHealth.HasValue)
                types[i++] = typeof(MaxHealth);
            if(MaxSpeed.HasValue)
                types[i++] = typeof(MaxSpeed);
            if(Position.HasValue)
                types[i++] = typeof(Position);
            if(Radius.HasValue)
                types[i++] = typeof(Radius);
            if(RandomSeed.HasValue)
                types[i++] = typeof(RandomSeed);
            if(RecivedDamage.HasValue)
                types[i++] = typeof(RecivedDamage);
            if(RockId.HasValue)
                types[i++] = typeof(RockId);
            if(Rotation.HasValue)
                types[i++] = typeof(Rotation);
            if(Separation.HasValue)
                types[i++] = typeof(Separation);
            if(Separator.HasValue)
                types[i++] = typeof(Separator);
            if(Squad.HasValue)
                types[i++] = typeof(Squad);
            if(SquadMember.HasValue)
                types[i++] = typeof(SquadMember);
            if(SquadMemberCount.HasValue)
                types[i++] = typeof(SquadMemberCount);
            if(SyncId.HasValue)
                types[i++] = typeof(SyncId);
            if(SyncIdReserve.HasValue)
                types[i++] = typeof(SyncIdReserve);
            if(Target.HasValue)
                types[i++] = typeof(Target);
            if(Targets.HasValue)
                types[i++] = typeof(Targets);
            if(TargetSearchDistance.HasValue)
                types[i++] = typeof(TargetSearchDistance);
            if(TargetSearchPosition.HasValue)
                types[i++] = typeof(TargetSearchPosition);
            if(TeamId.HasValue)
                types[i++] = typeof(TeamId);
            if(TreeId.HasValue)
                types[i++] = typeof(TreeId);
            if(UnitId.HasValue)
                types[i++] = typeof(UnitId);
            
            return types;
        }

        public void ForEach<T>(ref T action)
            where T: IStructGenericAction
        {

            if(AutoHeal.HasValue)
                action.Invoke<AutoHeal>();
            if(BehaviourConfig.HasValue)
                action.Invoke<BehaviourConfig>();
            if(BehaviourState.HasValue)
                action.Invoke<BehaviourState>();
            if(CachePosition.HasValue)
                action.Invoke<CachePosition>();
            if(CactusId.HasValue)
                action.Invoke<CactusId>();
            if(ClientId.HasValue)
                action.Invoke<ClientId>();
            if(Collide.HasValue)
                action.Invoke<Collide>();
            if(Damage.HasValue)
                action.Invoke<Damage>();
            if(Destination.HasValue)
                action.Invoke<Destination>();
            if(Direction.HasValue)
                action.Invoke<Direction>();
            if(Disposing.HasValue)
                action.Invoke<Disposing>();
            if(Fixation.HasValue)
                action.Invoke<Fixation>();
            if(FlyDestination.HasValue)
                action.Invoke<FlyDestination>();
            if(GoodsAmount.HasValue)
                action.Invoke<GoodsAmount>();
            if(GoodsCollectorRadius.HasValue)
                action.Invoke<GoodsCollectorRadius>();
            if(GoodsDrop.HasValue)
                action.Invoke<GoodsDrop>();
            if(GoodsId.HasValue)
                action.Invoke<GoodsId>();
            if(Health.HasValue)
                action.Invoke<Health>();
            if(HexMap.HasValue)
                action.Invoke<HexMap>();
            if(ImpactDistance.HasValue)
                action.Invoke<ImpactDistance>();
            if(Level.HasValue)
                action.Invoke<Level>();
            if(MaxHealth.HasValue)
                action.Invoke<MaxHealth>();
            if(MaxSpeed.HasValue)
                action.Invoke<MaxSpeed>();
            if(Position.HasValue)
                action.Invoke<Position>();
            if(Radius.HasValue)
                action.Invoke<Radius>();
            if(RandomSeed.HasValue)
                action.Invoke<RandomSeed>();
            if(RecivedDamage.HasValue)
                action.Invoke<RecivedDamage>();
            if(RockId.HasValue)
                action.Invoke<RockId>();
            if(Rotation.HasValue)
                action.Invoke<Rotation>();
            if(Separation.HasValue)
                action.Invoke<Separation>();
            if(Separator.HasValue)
                action.Invoke<Separator>();
            if(Squad.HasValue)
                action.Invoke<Squad>();
            if(SquadMember.HasValue)
                action.Invoke<SquadMember>();
            if(SquadMemberCount.HasValue)
                action.Invoke<SquadMemberCount>();
            if(SyncId.HasValue)
                action.Invoke<SyncId>();
            if(SyncIdReserve.HasValue)
                action.Invoke<SyncIdReserve>();
            if(Target.HasValue)
                action.Invoke<Target>();
            if(Targets.HasValue)
                action.Invoke<Targets>();
            if(TargetSearchDistance.HasValue)
                action.Invoke<TargetSearchDistance>();
            if(TargetSearchPosition.HasValue)
                action.Invoke<TargetSearchPosition>();
            if(TeamId.HasValue)
                action.Invoke<TeamId>();
            if(TreeId.HasValue)
                action.Invoke<TreeId>();
            if(UnitId.HasValue)
                action.Invoke<UnitId>();
        }
    }
}
