//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\ComponentGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


namespace DVG.Core.Components
{
    public static class ComponentIds
    {
        private static readonly Dictionary<Type, int> _typeToId;
        private static readonly Dictionary<int, Type> _idToType;

        static ComponentIds()
        {
            _typeToId = new Dictionary<Type, int>()
            {
            };
            
            _idToType = new Dictionary<int, Type>()
            {
            };
        }

        
        public static void ForEachData<T>(ref T action)
            where T: IStructGenericAction
        {
        }
    }
}

