//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\ComponentsRegistryGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using DVG.SkyPirates.Shared.Components.Runtime;
using DVG.SkyPirates.Shared.Components.Config;
using DVG.SkyPirates.Shared.Components.Framed;
using DVG.SkyPirates.Shared.Ids;
using DVG.Components;

namespace DVG.Components
{
    public static class ComponentsRegistry
    {
        public static void ForEachData<T>(ref T action)
            where T: IStructGenericAction
        {
            action.Invoke<AutoHeal>();
            action.Invoke<BehaviourConfig>();
            action.Invoke<BehaviourState>();
            action.Invoke<CachePosition>();
            action.Invoke<CactusId>();
            action.Invoke<ClientId>();
            action.Invoke<Collide>();
            action.Invoke<Damage>();
            action.Invoke<Destination>();
            action.Invoke<Direction>();
            action.Invoke<Disposing>();
            action.Invoke<Fixation>();
            action.Invoke<FlyDestination>();
            action.Invoke<GoodsAmount>();
            action.Invoke<GoodsCollectorRadius>();
            action.Invoke<GoodsDrop>();
            action.Invoke<GoodsId>();
            action.Invoke<Health>();
            action.Invoke<HexMap>();
            action.Invoke<ImpactDistance>();
            action.Invoke<Level>();
            action.Invoke<MaxHealth>();
            action.Invoke<MaxSpeed>();
            action.Invoke<Position>();
            action.Invoke<Radius>();
            action.Invoke<RandomSeed>();
            action.Invoke<RecivedDamage>();
            action.Invoke<RockId>();
            action.Invoke<Rotation>();
            action.Invoke<Separation>();
            action.Invoke<Separator>();
            action.Invoke<Squad>();
            action.Invoke<SquadMember>();
            action.Invoke<SquadMemberCount>();
            action.Invoke<SyncId>();
            action.Invoke<SyncIdReserve>();
            action.Invoke<Target>();
            action.Invoke<Targets>();
            action.Invoke<TargetSearchDistance>();
            action.Invoke<TargetSearchPosition>();
            action.Invoke<TeamId>();
            action.Invoke<TreeId>();
            action.Invoke<UnitId>();
        }
    }
}

