//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\ComponentsDataGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using System.Runtime.CompilerServices;

using DVG.SkyPirates.Shared.Components.Config;
using DVG.SkyPirates.Shared.Components.Runtime;
using DVG.SkyPirates.Shared.Components.Framed;
using DVG.SkyPirates.Shared.Ids;
using DVG.Components;

namespace DVG.SkyPirates.Shared.Data
{
    [Serializable]
    [DataContract]
    public sealed class ComponentsMask: IStructGenericCaller
    {

        [DataMember]
        private bool ActivityRange;
        [DataMember]
        private bool AutoHeal;
        [DataMember]
        private bool BehaviourConfig;
        [DataMember]
        private bool BehaviourState;
        [DataMember]
        private bool CachePosition;
        [DataMember]
        private bool CactusId;
        [DataMember]
        private bool ClientId;
        [DataMember]
        private bool Collide;
        [DataMember]
        private bool Damage;
        [DataMember]
        private bool Destination;
        [DataMember]
        private bool Direction;
        [DataMember]
        private bool Disposing;
        [DataMember]
        private bool Fixation;
        [DataMember]
        private bool FlyDestination;
        [DataMember]
        private bool GoodsAmount;
        [DataMember]
        private bool GoodsCollectorRadius;
        [DataMember]
        private bool GoodsDrop;
        [DataMember]
        private bool GoodsId;
        [DataMember]
        private bool Health;
        [DataMember]
        private bool HexMap;
        [DataMember]
        private bool ImpactDistance;
        [DataMember]
        private bool Level;
        [DataMember]
        private bool MaxHealth;
        [DataMember]
        private bool MaxSpeed;
        [DataMember]
        private bool Position;
        [DataMember]
        private bool Radius;
        [DataMember]
        private bool RandomSeed;
        [DataMember]
        private bool RecivedDamage;
        [DataMember]
        private bool RockId;
        [DataMember]
        private bool Rotation;
        [DataMember]
        private bool Separation;
        [DataMember]
        private bool Separator;
        [DataMember]
        private bool Squad;
        [DataMember]
        private bool SquadMember;
        [DataMember]
        private bool SquadMemberCount;
        [DataMember]
        private bool SyncId;
        [DataMember]
        private bool SyncIdReserve;
        [DataMember]
        private bool Target;
        [DataMember]
        private bool Targets;
        [DataMember]
        private bool TargetSearchDistance;
        [DataMember]
        private bool TargetSearchPosition;
        [DataMember]
        private bool TeamId;
        [DataMember]
        private bool TreeId;
        [DataMember]
        private bool UnitId;

        public bool Get<T>()
            where T : struct
        {
            Type type = typeof(T);

            if (type == typeof(ActivityRange))
                return ActivityRange;
            if (type == typeof(AutoHeal))
                return AutoHeal;
            if (type == typeof(BehaviourConfig))
                return BehaviourConfig;
            if (type == typeof(BehaviourState))
                return BehaviourState;
            if (type == typeof(CachePosition))
                return CachePosition;
            if (type == typeof(CactusId))
                return CactusId;
            if (type == typeof(ClientId))
                return ClientId;
            if (type == typeof(Collide))
                return Collide;
            if (type == typeof(Damage))
                return Damage;
            if (type == typeof(Destination))
                return Destination;
            if (type == typeof(Direction))
                return Direction;
            if (type == typeof(Disposing))
                return Disposing;
            if (type == typeof(Fixation))
                return Fixation;
            if (type == typeof(FlyDestination))
                return FlyDestination;
            if (type == typeof(GoodsAmount))
                return GoodsAmount;
            if (type == typeof(GoodsCollectorRadius))
                return GoodsCollectorRadius;
            if (type == typeof(GoodsDrop))
                return GoodsDrop;
            if (type == typeof(GoodsId))
                return GoodsId;
            if (type == typeof(Health))
                return Health;
            if (type == typeof(HexMap))
                return HexMap;
            if (type == typeof(ImpactDistance))
                return ImpactDistance;
            if (type == typeof(Level))
                return Level;
            if (type == typeof(MaxHealth))
                return MaxHealth;
            if (type == typeof(MaxSpeed))
                return MaxSpeed;
            if (type == typeof(Position))
                return Position;
            if (type == typeof(Radius))
                return Radius;
            if (type == typeof(RandomSeed))
                return RandomSeed;
            if (type == typeof(RecivedDamage))
                return RecivedDamage;
            if (type == typeof(RockId))
                return RockId;
            if (type == typeof(Rotation))
                return Rotation;
            if (type == typeof(Separation))
                return Separation;
            if (type == typeof(Separator))
                return Separator;
            if (type == typeof(Squad))
                return Squad;
            if (type == typeof(SquadMember))
                return SquadMember;
            if (type == typeof(SquadMemberCount))
                return SquadMemberCount;
            if (type == typeof(SyncId))
                return SyncId;
            if (type == typeof(SyncIdReserve))
                return SyncIdReserve;
            if (type == typeof(Target))
                return Target;
            if (type == typeof(Targets))
                return Targets;
            if (type == typeof(TargetSearchDistance))
                return TargetSearchDistance;
            if (type == typeof(TargetSearchPosition))
                return TargetSearchPosition;
            if (type == typeof(TeamId))
                return TeamId;
            if (type == typeof(TreeId))
                return TreeId;
            if (type == typeof(UnitId))
                return UnitId;

            throw new NotSupportedException(type.Name);
        }

        public void Set<T>(bool data)
            where T : struct
        {
            Type type = typeof(T);

            if (type == typeof(ActivityRange))
            {
                ActivityRange = data;
                return;
            }
            if (type == typeof(AutoHeal))
            {
                AutoHeal = data;
                return;
            }
            if (type == typeof(BehaviourConfig))
            {
                BehaviourConfig = data;
                return;
            }
            if (type == typeof(BehaviourState))
            {
                BehaviourState = data;
                return;
            }
            if (type == typeof(CachePosition))
            {
                CachePosition = data;
                return;
            }
            if (type == typeof(CactusId))
            {
                CactusId = data;
                return;
            }
            if (type == typeof(ClientId))
            {
                ClientId = data;
                return;
            }
            if (type == typeof(Collide))
            {
                Collide = data;
                return;
            }
            if (type == typeof(Damage))
            {
                Damage = data;
                return;
            }
            if (type == typeof(Destination))
            {
                Destination = data;
                return;
            }
            if (type == typeof(Direction))
            {
                Direction = data;
                return;
            }
            if (type == typeof(Disposing))
            {
                Disposing = data;
                return;
            }
            if (type == typeof(Fixation))
            {
                Fixation = data;
                return;
            }
            if (type == typeof(FlyDestination))
            {
                FlyDestination = data;
                return;
            }
            if (type == typeof(GoodsAmount))
            {
                GoodsAmount = data;
                return;
            }
            if (type == typeof(GoodsCollectorRadius))
            {
                GoodsCollectorRadius = data;
                return;
            }
            if (type == typeof(GoodsDrop))
            {
                GoodsDrop = data;
                return;
            }
            if (type == typeof(GoodsId))
            {
                GoodsId = data;
                return;
            }
            if (type == typeof(Health))
            {
                Health = data;
                return;
            }
            if (type == typeof(HexMap))
            {
                HexMap = data;
                return;
            }
            if (type == typeof(ImpactDistance))
            {
                ImpactDistance = data;
                return;
            }
            if (type == typeof(Level))
            {
                Level = data;
                return;
            }
            if (type == typeof(MaxHealth))
            {
                MaxHealth = data;
                return;
            }
            if (type == typeof(MaxSpeed))
            {
                MaxSpeed = data;
                return;
            }
            if (type == typeof(Position))
            {
                Position = data;
                return;
            }
            if (type == typeof(Radius))
            {
                Radius = data;
                return;
            }
            if (type == typeof(RandomSeed))
            {
                RandomSeed = data;
                return;
            }
            if (type == typeof(RecivedDamage))
            {
                RecivedDamage = data;
                return;
            }
            if (type == typeof(RockId))
            {
                RockId = data;
                return;
            }
            if (type == typeof(Rotation))
            {
                Rotation = data;
                return;
            }
            if (type == typeof(Separation))
            {
                Separation = data;
                return;
            }
            if (type == typeof(Separator))
            {
                Separator = data;
                return;
            }
            if (type == typeof(Squad))
            {
                Squad = data;
                return;
            }
            if (type == typeof(SquadMember))
            {
                SquadMember = data;
                return;
            }
            if (type == typeof(SquadMemberCount))
            {
                SquadMemberCount = data;
                return;
            }
            if (type == typeof(SyncId))
            {
                SyncId = data;
                return;
            }
            if (type == typeof(SyncIdReserve))
            {
                SyncIdReserve = data;
                return;
            }
            if (type == typeof(Target))
            {
                Target = data;
                return;
            }
            if (type == typeof(Targets))
            {
                Targets = data;
                return;
            }
            if (type == typeof(TargetSearchDistance))
            {
                TargetSearchDistance = data;
                return;
            }
            if (type == typeof(TargetSearchPosition))
            {
                TargetSearchPosition = data;
                return;
            }
            if (type == typeof(TeamId))
            {
                TeamId = data;
                return;
            }
            if (type == typeof(TreeId))
            {
                TreeId = data;
                return;
            }
            if (type == typeof(UnitId))
            {
                UnitId = data;
                return;
            }

            throw new NotSupportedException(type.Name);
        }

        public Type[] GetTypes()
        {
            int typesCount = 

                (ActivityRange? 1 : 0) + 
                (AutoHeal? 1 : 0) + 
                (BehaviourConfig? 1 : 0) + 
                (BehaviourState? 1 : 0) + 
                (CachePosition? 1 : 0) + 
                (CactusId? 1 : 0) + 
                (ClientId? 1 : 0) + 
                (Collide? 1 : 0) + 
                (Damage? 1 : 0) + 
                (Destination? 1 : 0) + 
                (Direction? 1 : 0) + 
                (Disposing? 1 : 0) + 
                (Fixation? 1 : 0) + 
                (FlyDestination? 1 : 0) + 
                (GoodsAmount? 1 : 0) + 
                (GoodsCollectorRadius? 1 : 0) + 
                (GoodsDrop? 1 : 0) + 
                (GoodsId? 1 : 0) + 
                (Health? 1 : 0) + 
                (HexMap? 1 : 0) + 
                (ImpactDistance? 1 : 0) + 
                (Level? 1 : 0) + 
                (MaxHealth? 1 : 0) + 
                (MaxSpeed? 1 : 0) + 
                (Position? 1 : 0) + 
                (Radius? 1 : 0) + 
                (RandomSeed? 1 : 0) + 
                (RecivedDamage? 1 : 0) + 
                (RockId? 1 : 0) + 
                (Rotation? 1 : 0) + 
                (Separation? 1 : 0) + 
                (Separator? 1 : 0) + 
                (Squad? 1 : 0) + 
                (SquadMember? 1 : 0) + 
                (SquadMemberCount? 1 : 0) + 
                (SyncId? 1 : 0) + 
                (SyncIdReserve? 1 : 0) + 
                (Target? 1 : 0) + 
                (Targets? 1 : 0) + 
                (TargetSearchDistance? 1 : 0) + 
                (TargetSearchPosition? 1 : 0) + 
                (TeamId? 1 : 0) + 
                (TreeId? 1 : 0) + 
                (UnitId? 1 : 0);
            
            Type[] types = new Type[typesCount];
            int i = 0;


            if(ActivityRange)
                types[i++] = typeof(ActivityRange);
            if(AutoHeal)
                types[i++] = typeof(AutoHeal);
            if(BehaviourConfig)
                types[i++] = typeof(BehaviourConfig);
            if(BehaviourState)
                types[i++] = typeof(BehaviourState);
            if(CachePosition)
                types[i++] = typeof(CachePosition);
            if(CactusId)
                types[i++] = typeof(CactusId);
            if(ClientId)
                types[i++] = typeof(ClientId);
            if(Collide)
                types[i++] = typeof(Collide);
            if(Damage)
                types[i++] = typeof(Damage);
            if(Destination)
                types[i++] = typeof(Destination);
            if(Direction)
                types[i++] = typeof(Direction);
            if(Disposing)
                types[i++] = typeof(Disposing);
            if(Fixation)
                types[i++] = typeof(Fixation);
            if(FlyDestination)
                types[i++] = typeof(FlyDestination);
            if(GoodsAmount)
                types[i++] = typeof(GoodsAmount);
            if(GoodsCollectorRadius)
                types[i++] = typeof(GoodsCollectorRadius);
            if(GoodsDrop)
                types[i++] = typeof(GoodsDrop);
            if(GoodsId)
                types[i++] = typeof(GoodsId);
            if(Health)
                types[i++] = typeof(Health);
            if(HexMap)
                types[i++] = typeof(HexMap);
            if(ImpactDistance)
                types[i++] = typeof(ImpactDistance);
            if(Level)
                types[i++] = typeof(Level);
            if(MaxHealth)
                types[i++] = typeof(MaxHealth);
            if(MaxSpeed)
                types[i++] = typeof(MaxSpeed);
            if(Position)
                types[i++] = typeof(Position);
            if(Radius)
                types[i++] = typeof(Radius);
            if(RandomSeed)
                types[i++] = typeof(RandomSeed);
            if(RecivedDamage)
                types[i++] = typeof(RecivedDamage);
            if(RockId)
                types[i++] = typeof(RockId);
            if(Rotation)
                types[i++] = typeof(Rotation);
            if(Separation)
                types[i++] = typeof(Separation);
            if(Separator)
                types[i++] = typeof(Separator);
            if(Squad)
                types[i++] = typeof(Squad);
            if(SquadMember)
                types[i++] = typeof(SquadMember);
            if(SquadMemberCount)
                types[i++] = typeof(SquadMemberCount);
            if(SyncId)
                types[i++] = typeof(SyncId);
            if(SyncIdReserve)
                types[i++] = typeof(SyncIdReserve);
            if(Target)
                types[i++] = typeof(Target);
            if(Targets)
                types[i++] = typeof(Targets);
            if(TargetSearchDistance)
                types[i++] = typeof(TargetSearchDistance);
            if(TargetSearchPosition)
                types[i++] = typeof(TargetSearchPosition);
            if(TeamId)
                types[i++] = typeof(TeamId);
            if(TreeId)
                types[i++] = typeof(TreeId);
            if(UnitId)
                types[i++] = typeof(UnitId);
            
            return types;
        }

        public void ForEach<T>(ref T action)
            where T: IStructGenericAction
        {

            if(ActivityRange)
                action.Invoke<ActivityRange>();
            if(AutoHeal)
                action.Invoke<AutoHeal>();
            if(BehaviourConfig)
                action.Invoke<BehaviourConfig>();
            if(BehaviourState)
                action.Invoke<BehaviourState>();
            if(CachePosition)
                action.Invoke<CachePosition>();
            if(CactusId)
                action.Invoke<CactusId>();
            if(ClientId)
                action.Invoke<ClientId>();
            if(Collide)
                action.Invoke<Collide>();
            if(Damage)
                action.Invoke<Damage>();
            if(Destination)
                action.Invoke<Destination>();
            if(Direction)
                action.Invoke<Direction>();
            if(Disposing)
                action.Invoke<Disposing>();
            if(Fixation)
                action.Invoke<Fixation>();
            if(FlyDestination)
                action.Invoke<FlyDestination>();
            if(GoodsAmount)
                action.Invoke<GoodsAmount>();
            if(GoodsCollectorRadius)
                action.Invoke<GoodsCollectorRadius>();
            if(GoodsDrop)
                action.Invoke<GoodsDrop>();
            if(GoodsId)
                action.Invoke<GoodsId>();
            if(Health)
                action.Invoke<Health>();
            if(HexMap)
                action.Invoke<HexMap>();
            if(ImpactDistance)
                action.Invoke<ImpactDistance>();
            if(Level)
                action.Invoke<Level>();
            if(MaxHealth)
                action.Invoke<MaxHealth>();
            if(MaxSpeed)
                action.Invoke<MaxSpeed>();
            if(Position)
                action.Invoke<Position>();
            if(Radius)
                action.Invoke<Radius>();
            if(RandomSeed)
                action.Invoke<RandomSeed>();
            if(RecivedDamage)
                action.Invoke<RecivedDamage>();
            if(RockId)
                action.Invoke<RockId>();
            if(Rotation)
                action.Invoke<Rotation>();
            if(Separation)
                action.Invoke<Separation>();
            if(Separator)
                action.Invoke<Separator>();
            if(Squad)
                action.Invoke<Squad>();
            if(SquadMember)
                action.Invoke<SquadMember>();
            if(SquadMemberCount)
                action.Invoke<SquadMemberCount>();
            if(SyncId)
                action.Invoke<SyncId>();
            if(SyncIdReserve)
                action.Invoke<SyncIdReserve>();
            if(Target)
                action.Invoke<Target>();
            if(Targets)
                action.Invoke<Targets>();
            if(TargetSearchDistance)
                action.Invoke<TargetSearchDistance>();
            if(TargetSearchPosition)
                action.Invoke<TargetSearchPosition>();
            if(TeamId)
                action.Invoke<TeamId>();
            if(TreeId)
                action.Invoke<TreeId>();
            if(UnitId)
                action.Invoke<UnitId>();
        }
    }
}
