//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\DisposableComponentsRegistryGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


namespace DVG.Components
{
    public static class DisposableComponentsRegistry
    {
        public static void ForEachData<T>(ref T action)
            where T: IStructGenericAction<IDisposable>
        {
        }
    }
}

