//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\EntityDataGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

using DVG.SkyPirates.Shared.Components;
using DVG.SkyPirates.Shared.Ids;
using DVG.SkyPirates.Shared.Components.Data;

namespace DVG.SkyPirates.Shared.Data
{
    [Serializable]
    [DataContract]
    public sealed class EntityData
    {

        [DataMember(Order = 0)]
        public Alive? Alive;
        [DataMember(Order = 1)]
        public AutoHeal? AutoHeal;
        [DataMember(Order = 2)]
        public Behaviour? Behaviour;
        [DataMember(Order = 3)]
        public BehaviourConfig? BehaviourConfig;
        [DataMember(Order = 4)]
        public CachePosition? CachePosition;
        [DataMember(Order = 5)]
        public CactusId? CactusId;
        [DataMember(Order = 6)]
        public CircleShape? CircleShape;
        [DataMember(Order = 7)]
        public Damage? Damage;
        [DataMember(Order = 8)]
        public Destination? Destination;
        [DataMember(Order = 9)]
        public Direction? Direction;
        [DataMember(Order = 10)]
        public Fixation? Fixation;
        [DataMember(Order = 11)]
        public Health? Health;
        [DataMember(Order = 12)]
        public HexMap? HexMap;
        [DataMember(Order = 13)]
        public ImpactDistance? ImpactDistance;
        [DataMember(Order = 14)]
        public Level? Level;
        [DataMember(Order = 15)]
        public MaxHealth? MaxHealth;
        [DataMember(Order = 16)]
        public MoveSpeed? MoveSpeed;
        [DataMember(Order = 17)]
        public Position? Position;
        [DataMember(Order = 18)]
        public RecivedDamage? RecivedDamage;
        [DataMember(Order = 19)]
        public RockId? RockId;
        [DataMember(Order = 20)]
        public Rotation? Rotation;
        [DataMember(Order = 21)]
        public Separation? Separation;
        [DataMember(Order = 22)]
        public Squad? Squad;
        [DataMember(Order = 23)]
        public Target? Target;
        [DataMember(Order = 24)]
        public Targets? Targets;
        [DataMember(Order = 25)]
        public TargetSearchData? TargetSearchData;
        [DataMember(Order = 26)]
        public Team? Team;
        [DataMember(Order = 27)]
        public TreeId? TreeId;
        [DataMember(Order = 28)]
        public UnitId? UnitId;

        public T? Get<T>()
            where T : struct
        {

            if (typeof(T) == typeof(Alive))
                return (Alive?)(object?)Alive;
            if (typeof(T) == typeof(AutoHeal))
                return (AutoHeal?)(object?)AutoHeal;
            if (typeof(T) == typeof(Behaviour))
                return (Behaviour?)(object?)Behaviour;
            if (typeof(T) == typeof(BehaviourConfig))
                return (BehaviourConfig?)(object?)BehaviourConfig;
            if (typeof(T) == typeof(CachePosition))
                return (CachePosition?)(object?)CachePosition;
            if (typeof(T) == typeof(CactusId))
                return (CactusId?)(object?)CactusId;
            if (typeof(T) == typeof(CircleShape))
                return (CircleShape?)(object?)CircleShape;
            if (typeof(T) == typeof(Damage))
                return (Damage?)(object?)Damage;
            if (typeof(T) == typeof(Destination))
                return (Destination?)(object?)Destination;
            if (typeof(T) == typeof(Direction))
                return (Direction?)(object?)Direction;
            if (typeof(T) == typeof(Fixation))
                return (Fixation?)(object?)Fixation;
            if (typeof(T) == typeof(Health))
                return (Health?)(object?)Health;
            if (typeof(T) == typeof(HexMap))
                return (HexMap?)(object?)HexMap;
            if (typeof(T) == typeof(ImpactDistance))
                return (ImpactDistance?)(object?)ImpactDistance;
            if (typeof(T) == typeof(Level))
                return (Level?)(object?)Level;
            if (typeof(T) == typeof(MaxHealth))
                return (MaxHealth?)(object?)MaxHealth;
            if (typeof(T) == typeof(MoveSpeed))
                return (MoveSpeed?)(object?)MoveSpeed;
            if (typeof(T) == typeof(Position))
                return (Position?)(object?)Position;
            if (typeof(T) == typeof(RecivedDamage))
                return (RecivedDamage?)(object?)RecivedDamage;
            if (typeof(T) == typeof(RockId))
                return (RockId?)(object?)RockId;
            if (typeof(T) == typeof(Rotation))
                return (Rotation?)(object?)Rotation;
            if (typeof(T) == typeof(Separation))
                return (Separation?)(object?)Separation;
            if (typeof(T) == typeof(Squad))
                return (Squad?)(object?)Squad;
            if (typeof(T) == typeof(Target))
                return (Target?)(object?)Target;
            if (typeof(T) == typeof(Targets))
                return (Targets?)(object?)Targets;
            if (typeof(T) == typeof(TargetSearchData))
                return (TargetSearchData?)(object?)TargetSearchData;
            if (typeof(T) == typeof(Team))
                return (Team?)(object?)Team;
            if (typeof(T) == typeof(TreeId))
                return (TreeId?)(object?)TreeId;
            if (typeof(T) == typeof(UnitId))
                return (UnitId?)(object?)UnitId;

            throw new NotSupportedException(typeof(T).Name);
        }

        public void Set<T>(T? data)
            where T : struct
        {

            if (typeof(T) == typeof(Alive))
            {
                Alive = (Alive?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(AutoHeal))
            {
                AutoHeal = (AutoHeal?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Behaviour))
            {
                Behaviour = (Behaviour?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(BehaviourConfig))
            {
                BehaviourConfig = (BehaviourConfig?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(CachePosition))
            {
                CachePosition = (CachePosition?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(CactusId))
            {
                CactusId = (CactusId?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(CircleShape))
            {
                CircleShape = (CircleShape?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Damage))
            {
                Damage = (Damage?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Destination))
            {
                Destination = (Destination?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Direction))
            {
                Direction = (Direction?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Fixation))
            {
                Fixation = (Fixation?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Health))
            {
                Health = (Health?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(HexMap))
            {
                HexMap = (HexMap?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(ImpactDistance))
            {
                ImpactDistance = (ImpactDistance?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Level))
            {
                Level = (Level?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(MaxHealth))
            {
                MaxHealth = (MaxHealth?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(MoveSpeed))
            {
                MoveSpeed = (MoveSpeed?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Position))
            {
                Position = (Position?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(RecivedDamage))
            {
                RecivedDamage = (RecivedDamage?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(RockId))
            {
                RockId = (RockId?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Rotation))
            {
                Rotation = (Rotation?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Separation))
            {
                Separation = (Separation?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Squad))
            {
                Squad = (Squad?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Target))
            {
                Target = (Target?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Targets))
            {
                Targets = (Targets?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(TargetSearchData))
            {
                TargetSearchData = (TargetSearchData?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(Team))
            {
                Team = (Team?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(TreeId))
            {
                TreeId = (TreeId?)(object?)data;
                return;
            }
            if (typeof(T) == typeof(UnitId))
            {
                UnitId = (UnitId?)(object?)data;
                return;
            }

            throw new NotSupportedException(typeof(T).Name);
        }
    }
}
