//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\FramedComponentsRegistryGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using DVG.SkyPirates.Shared.Components.Framed;

namespace DVG.Components
{
    public static class FramedComponentsRegistry
    {
        public static void ForEachData<T>(ref T action)
            where T: IStructGenericAction
        {
            action.Invoke<CachePosition>();
            action.Invoke<Collide>();
            action.Invoke<Destination>();
            action.Invoke<RecivedDamage>();
            action.Invoke<SquadMemberCount>();
            action.Invoke<Target>();
            action.Invoke<Targets>();
            action.Invoke<TargetSearchPosition>();
        }
    }
}

