//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\StringIdConstantsGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DVG.SkyPirates.Shared.Ids
{
    partial struct GoodsId
    {
        public static partial class Constants
        {

            private static readonly GoodsId[] _allIds = new GoodsId[]
            {
            };
            public static ReadOnlySpan<GoodsId> AllIds => _allIds;
        }
    }
}
