//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\HistoryComponentsRegistryGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using DVG.SkyPirates.Shared.Components.Runtime;
using DVG.SkyPirates.Shared.Components.Config;
using DVG.SkyPirates.Shared.Ids;
using DVG.SkyPirates.Shared.Components.Special;

namespace DVG.Core.Components
{
    public static class HistoryComponentsRegistry
    {
        public static void ForEachData<T>(ref T action)
            where T: IStructGenericAction
        {
            action.Invoke<AutoHeal>();
            action.Invoke<BehaviourConfig>();
            action.Invoke<BehaviourState>();
            action.Invoke<CactusId>();
            action.Invoke<Damage>();
            action.Invoke<Direction>();
            action.Invoke<Dispose>();
            action.Invoke<Fixation>();
            action.Invoke<Health>();
            action.Invoke<HexMap>();
            action.Invoke<ImpactDistance>();
            action.Invoke<Level>();
            action.Invoke<MaxHealth>();
            action.Invoke<MaxSpeed>();
            action.Invoke<Position>();
            action.Invoke<Radius>();
            action.Invoke<RockId>();
            action.Invoke<Rotation>();
            action.Invoke<Separation>();
            action.Invoke<Squad>();
            action.Invoke<SquadMember>();
            action.Invoke<SyncId>();
            action.Invoke<TargetSearchDistance>();
            action.Invoke<Team>();
            action.Invoke<TreeId>();
            action.Invoke<UnitId>();
        }
    }
}

