//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\HistoryGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using DVG.SkyPirates.Shared.Components;
using DVG.SkyPirates.Shared.Components.Data;
using DVG.SkyPirates.Shared.Components.Special;
using DVG.SkyPirates.Shared.Ids;

namespace DVG.Core.History
{
    public static class HistoryIds
    {
        private static readonly Dictionary<Type, int> _typeToId;
        private static readonly Dictionary<int, Type> _idToType;

        static HistoryIds()
        {
            _typeToId = new Dictionary<Type, int>()
            {
                {typeof(Alive), 1},
                {typeof(AutoHeal), 2},
                {typeof(Behaviour), 3},
                {typeof(CircleShape), 4},
                {typeof(Damage), 5},
                {typeof(Destination), 6},
                {typeof(Destruct), 7},
                {typeof(Direction), 8},
                {typeof(Fixation), 9},
                {typeof(Health), 10},
                {typeof(ImpactDistance), 11},
                {typeof(MaxHealth), 12},
                {typeof(MoveSpeed), 13},
                {typeof(Position), 14},
                {typeof(Rotation), 15},
                {typeof(Separation), 16},
                {typeof(Squad), 17},
                {typeof(Target), 18},
                {typeof(TargetSearchData), 19},
                {typeof(Team), 20},
                {typeof(UnitId), 21},
            };
            
            _idToType = new Dictionary<int, Type>()
            {
                {1, typeof(Alive)},
                {2, typeof(AutoHeal)},
                {3, typeof(Behaviour)},
                {4, typeof(CircleShape)},
                {5, typeof(Damage)},
                {6, typeof(Destination)},
                {7, typeof(Destruct)},
                {8, typeof(Direction)},
                {9, typeof(Fixation)},
                {10, typeof(Health)},
                {11, typeof(ImpactDistance)},
                {12, typeof(MaxHealth)},
                {13, typeof(MoveSpeed)},
                {14, typeof(Position)},
                {15, typeof(Rotation)},
                {16, typeof(Separation)},
                {17, typeof(Squad)},
                {18, typeof(Target)},
                {19, typeof(TargetSearchData)},
                {20, typeof(Team)},
                {21, typeof(UnitId)},
            };
        }

        
        public static void ForEachData<T>(ref T action)
            where T: IStructGenericAction
        {
            action.Invoke<Alive>();
            action.Invoke<AutoHeal>();
            action.Invoke<Behaviour>();
            action.Invoke<CircleShape>();
            action.Invoke<Damage>();
            action.Invoke<Destination>();
            action.Invoke<Destruct>();
            action.Invoke<Direction>();
            action.Invoke<Fixation>();
            action.Invoke<Health>();
            action.Invoke<ImpactDistance>();
            action.Invoke<MaxHealth>();
            action.Invoke<MoveSpeed>();
            action.Invoke<Position>();
            action.Invoke<Rotation>();
            action.Invoke<Separation>();
            action.Invoke<Squad>();
            action.Invoke<Target>();
            action.Invoke<TargetSearchData>();
            action.Invoke<Team>();
            action.Invoke<UnitId>();
        }

        public static int GetId<T>() => _typeToId[typeof(T)];
        public static Type GetCommand(ushort id) => _idToType[id];
    }
}

