//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\HistoryGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using DVG.SkyPirates.Shared.Components;
using DVG.SkyPirates.Shared.Components.Data;

namespace DVG.Core.History
{
    public static class HistoryIds
    {
        private static readonly Dictionary<Type, int> _typeToId;
        private static readonly Dictionary<int, Type> _idToType;

        static HistoryIds()
        {
            _typeToId = new Dictionary<Type, int>()
            {
                {typeof(Behaviour), 1},
                {typeof(Damage), 2},
                {typeof(Destination), 3},
                {typeof(Direction), 4},
                {typeof(Fixation), 5},
                {typeof(Health), 6},
                {typeof(ImpactDistance), 7},
                {typeof(MoveSpeed), 8},
                {typeof(Position), 9},
                {typeof(Rotation), 10},
                {typeof(Squad), 11},
                {typeof(Target), 12},
                {typeof(TargetSearchData), 13},
                {typeof(Team), 14},
            };
            
            _idToType = new Dictionary<int, Type>()
            {
                {1, typeof(Behaviour)},
                {2, typeof(Damage)},
                {3, typeof(Destination)},
                {4, typeof(Direction)},
                {5, typeof(Fixation)},
                {6, typeof(Health)},
                {7, typeof(ImpactDistance)},
                {8, typeof(MoveSpeed)},
                {9, typeof(Position)},
                {10, typeof(Rotation)},
                {11, typeof(Squad)},
                {12, typeof(Target)},
                {13, typeof(TargetSearchData)},
                {14, typeof(Team)},
            };
        }

        
        public static void ForEachData<T>(T action)
            where T: IStructGenericAction
        {
            action.Invoke<Behaviour>();
            action.Invoke<Damage>();
            action.Invoke<Destination>();
            action.Invoke<Direction>();
            action.Invoke<Fixation>();
            action.Invoke<Health>();
            action.Invoke<ImpactDistance>();
            action.Invoke<MoveSpeed>();
            action.Invoke<Position>();
            action.Invoke<Rotation>();
            action.Invoke<Squad>();
            action.Invoke<Target>();
            action.Invoke<TargetSearchData>();
            action.Invoke<Team>();
        }

        public static int GetId<T>() => _typeToId[typeof(T)];
        public static Type GetCommand(ushort id) => _idToType[id];
    }
}

