//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\CommandGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using DVG.Commands;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;

namespace DVG.SkyPirates.Shared.Commands
{
    [StructLayout(LayoutKind.Sequential)]
    partial struct JoystickCommand : ICommandData
    {
        [IgnoreDataMember]
        public int CommandId => CommandIds.GetId<JoystickCommand>();
    }
}
