//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\NewTypePatternGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using DVG.NewType;

namespace DVG.SkyPirates.Shared.Components.Framed
{
    partial struct CachePosition : INewType<DVG.fix3>
    {
        
        DVG.fix3 INewType<DVG.fix3>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator CachePosition(DVG.fix3 value)
            => new() { Value = value };

        public static implicit operator DVG.fix3(CachePosition newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct Damage : INewType<DVG.fix>
    {
        
        DVG.fix INewType<DVG.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Damage(DVG.fix value)
            => new() { Value = value };

        public static implicit operator DVG.fix(Damage newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct Direction : INewType<DVG.fix2>
    {
        
        DVG.fix2 INewType<DVG.fix2>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Direction(DVG.fix2 value)
            => new() { Value = value };

        public static implicit operator DVG.fix2(Direction newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct Fixation : INewType<System.Boolean>
    {
        
        System.Boolean INewType<System.Boolean>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Fixation(System.Boolean value)
            => new() { Value = value };

        public static implicit operator System.Boolean(Fixation newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct GoodsAmount : INewType<System.Int32>
    {
        
        System.Int32 INewType<System.Int32>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator GoodsAmount(System.Int32 value)
            => new() { Value = value };

        public static implicit operator System.Int32(GoodsAmount newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct GoodsCollectorRadius : INewType<DVG.fix>
    {
        
        DVG.fix INewType<DVG.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator GoodsCollectorRadius(DVG.fix value)
            => new() { Value = value };

        public static implicit operator DVG.fix(GoodsCollectorRadius newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct Health : INewType<DVG.fix>
    {
        
        DVG.fix INewType<DVG.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Health(DVG.fix value)
            => new() { Value = value };

        public static implicit operator DVG.fix(Health newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct ImpactDistance : INewType<DVG.fix>
    {
        
        DVG.fix INewType<DVG.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator ImpactDistance(DVG.fix value)
            => new() { Value = value };

        public static implicit operator DVG.fix(ImpactDistance newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct Level : INewType<System.Int32>
    {
        
        System.Int32 INewType<System.Int32>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Level(System.Int32 value)
            => new() { Value = value };

        public static implicit operator System.Int32(Level newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct MaxHealth : INewType<DVG.fix>
    {
        
        DVG.fix INewType<DVG.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator MaxHealth(DVG.fix value)
            => new() { Value = value };

        public static implicit operator DVG.fix(MaxHealth newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct MaxSpeed : INewType<DVG.fix>
    {
        
        DVG.fix INewType<DVG.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator MaxSpeed(DVG.fix value)
            => new() { Value = value };

        public static implicit operator DVG.fix(MaxSpeed newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct Position : INewType<DVG.fix3>
    {
        
        DVG.fix3 INewType<DVG.fix3>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Position(DVG.fix3 value)
            => new() { Value = value };

        public static implicit operator DVG.fix3(Position newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct Radius : INewType<DVG.fix>
    {
        
        DVG.fix INewType<DVG.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Radius(DVG.fix value)
            => new() { Value = value };

        public static implicit operator DVG.fix(Radius newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Framed
{
    partial struct RecivedDamage : INewType<DVG.fix>
    {
        
        DVG.fix INewType<DVG.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator RecivedDamage(DVG.fix value)
            => new() { Value = value };

        public static implicit operator DVG.fix(RecivedDamage newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct Rotation : INewType<DVG.fix>
    {
        
        DVG.fix INewType<DVG.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Rotation(DVG.fix value)
            => new() { Value = value };

        public static implicit operator DVG.fix(Rotation newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct Separation : INewType<DVG.fix>
    {
        
        DVG.fix INewType<DVG.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Separation(DVG.fix value)
            => new() { Value = value };

        public static implicit operator DVG.fix(Separation newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Framed
{
    partial struct SquadMemberCount : INewType<System.Int32>
    {
        
        System.Int32 INewType<System.Int32>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator SquadMemberCount(System.Int32 value)
            => new() { Value = value };

        public static implicit operator System.Int32(SquadMemberCount newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct TargetSearchDistance : INewType<DVG.fix>
    {
        
        DVG.fix INewType<DVG.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator TargetSearchDistance(DVG.fix value)
            => new() { Value = value };

        public static implicit operator DVG.fix(TargetSearchDistance newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Framed
{
    partial struct TargetSearchPosition : INewType<DVG.fix3>
    {
        
        DVG.fix3 INewType<DVG.fix3>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator TargetSearchPosition(DVG.fix3 value)
            => new() { Value = value };

        public static implicit operator DVG.fix3(TargetSearchPosition newType)
            => newType.Value;
    }
}

