//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\NewTypePatternGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using DVG.NewType;

namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct ActivityRange : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator ActivityRange(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(ActivityRange newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Framed
{
    partial struct CachePosition : INewType<Delta.fix3>
    {
        
        Delta.fix3 INewType<Delta.fix3>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator CachePosition(Delta.fix3 value)
            => new() { Value = value };

        public static implicit operator Delta.fix3(CachePosition newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct Damage : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Damage(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(Damage newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct Direction : INewType<Delta.fix2>
    {
        
        Delta.fix2 INewType<Delta.fix2>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Direction(Delta.fix2 value)
            => new() { Value = value };

        public static implicit operator Delta.fix2(Direction newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct Fixation : INewType<System.Boolean>
    {
        
        System.Boolean INewType<System.Boolean>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Fixation(System.Boolean value)
            => new() { Value = value };

        public static implicit operator System.Boolean(Fixation newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct GoodsAmount : INewType<System.Int32>
    {
        
        System.Int32 INewType<System.Int32>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator GoodsAmount(System.Int32 value)
            => new() { Value = value };

        public static implicit operator System.Int32(GoodsAmount newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct GoodsCollectorRadius : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator GoodsCollectorRadius(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(GoodsCollectorRadius newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct Health : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Health(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(Health newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct ImpactDistance : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator ImpactDistance(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(ImpactDistance newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct Level : INewType<System.Int32>
    {
        
        System.Int32 INewType<System.Int32>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Level(System.Int32 value)
            => new() { Value = value };

        public static implicit operator System.Int32(Level newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct MaxHealth : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator MaxHealth(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(MaxHealth newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct MaxSpeed : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator MaxSpeed(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(MaxSpeed newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct Position : INewType<Delta.fix3>
    {
        
        Delta.fix3 INewType<Delta.fix3>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Position(Delta.fix3 value)
            => new() { Value = value };

        public static implicit operator Delta.fix3(Position newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct Radius : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Radius(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(Radius newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Framed
{
    partial struct RecivedDamage : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator RecivedDamage(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(RecivedDamage newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct Rotation : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Rotation(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(Rotation newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct Separation : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator Separation(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(Separation newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Framed
{
    partial struct SquadMemberCount : INewType<System.Int32>
    {
        
        System.Int32 INewType<System.Int32>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator SquadMemberCount(System.Int32 value)
            => new() { Value = value };

        public static implicit operator System.Int32(SquadMemberCount newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Config
{
    partial struct TargetSearchDistance : INewType<Delta.fix>
    {
        
        Delta.fix INewType<Delta.fix>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator TargetSearchDistance(Delta.fix value)
            => new() { Value = value };

        public static implicit operator Delta.fix(TargetSearchDistance newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Framed
{
    partial struct TargetSearchPosition : INewType<Delta.fix3>
    {
        
        Delta.fix3 INewType<Delta.fix3>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator TargetSearchPosition(Delta.fix3 value)
            => new() { Value = value };

        public static implicit operator Delta.fix3(TargetSearchPosition newType)
            => newType.Value;
    }
}


namespace DVG.SkyPirates.Shared.Components.Runtime
{
    partial struct TeamId : INewType<System.Int32>
    {
        
        System.Int32 INewType<System.Int32>.Value { readonly get => Value; set => Value = value; }

        public static implicit operator TeamId(System.Int32 value)
            => new() { Value = value };

        public static implicit operator System.Int32(TeamId newType)
            => newType.Value;
    }
}

