//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\StringIdConstantsGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DVG.SkyPirates.Shared.Ids
{
    partial struct RockId
    {
        public static partial class Constants
        {
            public static readonly RockId HardRock_01 = new RockId("HardRock_01");
            public static readonly RockId HardRock_02 = new RockId("HardRock_02");
            public static readonly RockId HardRock_03 = new RockId("HardRock_03");
            public static readonly RockId HardRock_04 = new RockId("HardRock_04");
            public static readonly RockId HardRock_05 = new RockId("HardRock_05");
            public static readonly RockId HardRock_06 = new RockId("HardRock_06");
            public static readonly RockId HardRock_07 = new RockId("HardRock_07");
            public static readonly RockId HardRock_08 = new RockId("HardRock_08");
            public static readonly RockId HardRock_09 = new RockId("HardRock_09");
            public static readonly RockId HardRock_10 = new RockId("HardRock_10");
            public static readonly RockId HardRock_11 = new RockId("HardRock_11");
            public static readonly RockId HardRock_12 = new RockId("HardRock_12");
            public static readonly RockId HardRock_13 = new RockId("HardRock_13");
            public static readonly RockId HardRock_14 = new RockId("HardRock_14");
            public static readonly RockId HardRock_15 = new RockId("HardRock_15");
            public static readonly RockId HardRock_16 = new RockId("HardRock_16");
            public static readonly RockId HardRock_17 = new RockId("HardRock_17");
            public static readonly RockId HardRock_18 = new RockId("HardRock_18");
            public static readonly RockId HardRock_19 = new RockId("HardRock_19");
            public static readonly RockId HardRock_20 = new RockId("HardRock_20");
            public static readonly RockId HardRock_21 = new RockId("HardRock_21");
            public static readonly RockId HardRock_22 = new RockId("HardRock_22");
            public static readonly RockId HardRock_23 = new RockId("HardRock_23");
            public static readonly RockId HardRock_24 = new RockId("HardRock_24");
            public static readonly RockId HardRock_25 = new RockId("HardRock_25");
            public static readonly RockId HardRock_26 = new RockId("HardRock_26");
            public static readonly RockId HardRock_27 = new RockId("HardRock_27");
            public static readonly RockId HardRock_28 = new RockId("HardRock_28");
            public static readonly RockId HardRock_29 = new RockId("HardRock_29");
            public static readonly RockId HardRock_30 = new RockId("HardRock_30");
            public static readonly RockId HardRock_31 = new RockId("HardRock_31");
            public static readonly RockId HardRock_32 = new RockId("HardRock_32");
            public static readonly RockId HardRock_33 = new RockId("HardRock_33");
            public static readonly RockId HardRock_34 = new RockId("HardRock_34");
            public static readonly RockId HardRock_35 = new RockId("HardRock_35");
            public static readonly RockId HardRock_36 = new RockId("HardRock_36");
            public static readonly RockId HardRock_37 = new RockId("HardRock_37");
            public static readonly RockId HardRock_38 = new RockId("HardRock_38");
            public static readonly RockId HardRock_39 = new RockId("HardRock_39");
            public static readonly RockId HardRock_40 = new RockId("HardRock_40");
            public static readonly RockId HardRock_41 = new RockId("HardRock_41");
            public static readonly RockId HardRock_42 = new RockId("HardRock_42");
            public static readonly RockId HardRock_43 = new RockId("HardRock_43");
            public static readonly RockId HardRock_44 = new RockId("HardRock_44");
            public static readonly RockId HardRock_45 = new RockId("HardRock_45");
            public static readonly RockId HardRock_46 = new RockId("HardRock_46");
            public static readonly RockId HardRock_47 = new RockId("HardRock_47");
            public static readonly RockId HardRock_48 = new RockId("HardRock_48");
            public static readonly RockId HardRock_49 = new RockId("HardRock_49");
            public static readonly RockId HardRock_50 = new RockId("HardRock_50");
            public static readonly RockId HardRock_51 = new RockId("HardRock_51");
            public static readonly RockId HardRock_52 = new RockId("HardRock_52");
            public static readonly RockId HardRock_53 = new RockId("HardRock_53");
            public static readonly RockId HardRock_54 = new RockId("HardRock_54");
            public static readonly RockId HardRock_55 = new RockId("HardRock_55");
            public static readonly RockId HardRock_56 = new RockId("HardRock_56");
            public static readonly RockId HardRock_57 = new RockId("HardRock_57");
            public static readonly RockId HardRock_58 = new RockId("HardRock_58");
            public static readonly RockId HardRock_59 = new RockId("HardRock_59");
            public static readonly RockId HardRock_60 = new RockId("HardRock_60");
            public static readonly RockId SoftRock_32 = new RockId("SoftRock_32");
            public static readonly RockId SoftRock_01 = new RockId("SoftRock_01");
            public static readonly RockId SoftRock_02 = new RockId("SoftRock_02");
            public static readonly RockId SoftRock_03 = new RockId("SoftRock_03");
            public static readonly RockId SoftRock_04 = new RockId("SoftRock_04");
            public static readonly RockId SoftRock_05 = new RockId("SoftRock_05");
            public static readonly RockId SoftRock_06 = new RockId("SoftRock_06");
            public static readonly RockId SoftRock_07 = new RockId("SoftRock_07");
            public static readonly RockId SoftRock_08 = new RockId("SoftRock_08");
            public static readonly RockId SoftRock_09 = new RockId("SoftRock_09");
            public static readonly RockId SoftRock_10 = new RockId("SoftRock_10");
            public static readonly RockId SoftRock_11 = new RockId("SoftRock_11");
            public static readonly RockId SoftRock_12 = new RockId("SoftRock_12");
            public static readonly RockId SoftRock_13 = new RockId("SoftRock_13");
            public static readonly RockId SoftRock_14 = new RockId("SoftRock_14");
            public static readonly RockId SoftRock_15 = new RockId("SoftRock_15");
            public static readonly RockId SoftRock_16 = new RockId("SoftRock_16");
            public static readonly RockId SoftRock_17 = new RockId("SoftRock_17");
            public static readonly RockId SoftRock_18 = new RockId("SoftRock_18");
            public static readonly RockId SoftRock_19 = new RockId("SoftRock_19");
            public static readonly RockId SoftRock_20 = new RockId("SoftRock_20");
            public static readonly RockId SoftRock_21 = new RockId("SoftRock_21");
            public static readonly RockId SoftRock_22 = new RockId("SoftRock_22");
            public static readonly RockId SoftRock_23 = new RockId("SoftRock_23");
            public static readonly RockId SoftRock_24 = new RockId("SoftRock_24");
            public static readonly RockId SoftRock_25 = new RockId("SoftRock_25");
            public static readonly RockId SoftRock_26 = new RockId("SoftRock_26");
            public static readonly RockId SoftRock_27 = new RockId("SoftRock_27");
            public static readonly RockId SoftRock_28 = new RockId("SoftRock_28");
            public static readonly RockId SoftRock_29 = new RockId("SoftRock_29");
            public static readonly RockId SoftRock_30 = new RockId("SoftRock_30");
            public static readonly RockId SoftRock_31 = new RockId("SoftRock_31");

            private static readonly RockId[] _allIds = new RockId[]
            {
                new RockId("HardRock_01"),
                new RockId("HardRock_02"),
                new RockId("HardRock_03"),
                new RockId("HardRock_04"),
                new RockId("HardRock_05"),
                new RockId("HardRock_06"),
                new RockId("HardRock_07"),
                new RockId("HardRock_08"),
                new RockId("HardRock_09"),
                new RockId("HardRock_10"),
                new RockId("HardRock_11"),
                new RockId("HardRock_12"),
                new RockId("HardRock_13"),
                new RockId("HardRock_14"),
                new RockId("HardRock_15"),
                new RockId("HardRock_16"),
                new RockId("HardRock_17"),
                new RockId("HardRock_18"),
                new RockId("HardRock_19"),
                new RockId("HardRock_20"),
                new RockId("HardRock_21"),
                new RockId("HardRock_22"),
                new RockId("HardRock_23"),
                new RockId("HardRock_24"),
                new RockId("HardRock_25"),
                new RockId("HardRock_26"),
                new RockId("HardRock_27"),
                new RockId("HardRock_28"),
                new RockId("HardRock_29"),
                new RockId("HardRock_30"),
                new RockId("HardRock_31"),
                new RockId("HardRock_32"),
                new RockId("HardRock_33"),
                new RockId("HardRock_34"),
                new RockId("HardRock_35"),
                new RockId("HardRock_36"),
                new RockId("HardRock_37"),
                new RockId("HardRock_38"),
                new RockId("HardRock_39"),
                new RockId("HardRock_40"),
                new RockId("HardRock_41"),
                new RockId("HardRock_42"),
                new RockId("HardRock_43"),
                new RockId("HardRock_44"),
                new RockId("HardRock_45"),
                new RockId("HardRock_46"),
                new RockId("HardRock_47"),
                new RockId("HardRock_48"),
                new RockId("HardRock_49"),
                new RockId("HardRock_50"),
                new RockId("HardRock_51"),
                new RockId("HardRock_52"),
                new RockId("HardRock_53"),
                new RockId("HardRock_54"),
                new RockId("HardRock_55"),
                new RockId("HardRock_56"),
                new RockId("HardRock_57"),
                new RockId("HardRock_58"),
                new RockId("HardRock_59"),
                new RockId("HardRock_60"),
                new RockId("SoftRock_32"),
                new RockId("SoftRock_01"),
                new RockId("SoftRock_02"),
                new RockId("SoftRock_03"),
                new RockId("SoftRock_04"),
                new RockId("SoftRock_05"),
                new RockId("SoftRock_06"),
                new RockId("SoftRock_07"),
                new RockId("SoftRock_08"),
                new RockId("SoftRock_09"),
                new RockId("SoftRock_10"),
                new RockId("SoftRock_11"),
                new RockId("SoftRock_12"),
                new RockId("SoftRock_13"),
                new RockId("SoftRock_14"),
                new RockId("SoftRock_15"),
                new RockId("SoftRock_16"),
                new RockId("SoftRock_17"),
                new RockId("SoftRock_18"),
                new RockId("SoftRock_19"),
                new RockId("SoftRock_20"),
                new RockId("SoftRock_21"),
                new RockId("SoftRock_22"),
                new RockId("SoftRock_23"),
                new RockId("SoftRock_24"),
                new RockId("SoftRock_25"),
                new RockId("SoftRock_26"),
                new RockId("SoftRock_27"),
                new RockId("SoftRock_28"),
                new RockId("SoftRock_29"),
                new RockId("SoftRock_30"),
                new RockId("SoftRock_31"),
            };
            public static ReadOnlySpan<RockId> AllIds => _allIds;
        }
    }
}
