//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\StringIdGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using DVG.Ids;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace DVG.SkyPirates.Shared.Ids
{
    [Serializable]
    partial struct StateId : IId, IEquatable<StateId>, IComparable<StateId>
    {
        private int _value;
        public string Value;
        string IId.Value => Value;
        public static readonly StateId None = new StateId("None");
        [IgnoreDataMember]
        public readonly bool IsNone => _value == 0;

        public StateId(string value)
        {
            Value = value;
            _value = Registry.GetOrCreate(Value);
        }

        public readonly bool Equals(StateId other) => _value == other._value;
        public readonly int CompareTo(StateId other) => Registry.Compare(this, other);
        public override readonly bool Equals(object obj) => obj is StateId other && Equals(other);
        public override readonly int GetHashCode() => _value;
        public override readonly string ToString() => Value;

        public static bool operator ==(StateId a, StateId b) => a.Equals(b);
        public static bool operator !=(StateId a, StateId b) => !a.Equals(b);

        public static implicit operator StateId(string value) => new(value);
        public static implicit operator string(StateId id) => id.ToString();

        private static class Registry
        {
            private static readonly Dictionary<string, int> _stringToId = new(StringComparer.Ordinal)
            {
                ["None"] = 0,
            };
            private static readonly Dictionary<int, string> _idToString = new()
            {
                [0] = "None"
            };
            private static readonly Dictionary<(int, int), int> _comparisonCache = new();
            private static int _counter = 1;

            public static int Compare(StateId lhs, StateId rhs)
            {
                if (lhs == rhs)
                    return 0;
                var lkey = (lhs._value, rhs._value);
                if(!_comparisonCache.TryGetValue(lkey, out var comparison))
                {
                    comparison = string.Compare(lhs.Value, rhs.Value, StringComparison.OrdinalIgnoreCase);
                    _comparisonCache.Add(lkey, comparison);
                    _comparisonCache.Add((rhs._value, lhs._value), -comparison);
                }
                return comparison;
            }

            public static int GetOrCreate(string value)
            {
                if (string.IsNullOrWhiteSpace(value))
                    return 0;

                if (_stringToId.TryGetValue(value, out var existing))
                    return existing;

                var id = _counter++;
                _stringToId[value] = id;
                _idToString[id] = value;
                return id;
            }
        }
    }
}
