//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\StringIdGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using DVG.Core;
using System;
using System.Runtime.Serialization;

namespace DVG.SkyPirates.Shared.Ids
{
    [Serializable]
    [DataContract]
    readonly partial struct StateId : IId, IEquatable<StateId>, IComparable<StateId>
    {
        [DataMember(Order = 0)]
        public string Value { get; }
        private const string NoneValue = "None";
        public static readonly StateId None = new StateId(NoneValue);

        public StateId(string value)
        {
            Value = value;
        }

        public readonly bool IsNone => string.IsNullOrEmpty(Value) || Value == NoneValue;
        public readonly bool Equals(StateId other) => Value == other.Value || (IsNone && other.IsNone);
        public readonly int CompareTo(StateId other) => Equals(other) ? 0 : string.Compare(Value, other.Value);
        public override readonly bool Equals(object obj) => obj is StateId other && Equals(other);
        public override readonly string ToString() => Value;
        //public override readonly int GetHashCode() => IsNone ? 0 : Value.GetHashCode();
        public static bool operator ==(StateId a, StateId b) => a.Value == b.Value || (a.IsNone && b.IsNone);
        public static bool operator !=(StateId a, StateId b) => !(a == b);

        public static implicit operator string(StateId id) => id.Value;
    }
}
