//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\StringIdGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using DVG.Ids;
using System;
using System.Runtime.Serialization;

namespace DVG.SkyPirates.Shared.Ids
{
    [Serializable]
    [DataContract]
    partial struct StateId : IId, IEquatable<StateId>, IComparable<StateId>
    {
        [DataMember(Order = 0)]
        public string Value;
        string IId.Value => Value;
        private const string NoneValue = "None";
        public static readonly StateId None = new StateId(NoneValue);

        public StateId(string value)
        {
            Value = value;
        }

        [IgnoreDataMember]
        public readonly bool IsNone => string.IsNullOrWhiteSpace(Value) || string.Equals(Value, NoneValue, StringComparison.Ordinal);
        public readonly bool Equals(StateId other) => (IsNone && other.IsNone) || string.Equals(Value, other.Value, StringComparison.Ordinal);
        public readonly int CompareTo(StateId other) => Equals(other) ? 0 : string.Compare(Value, other.Value, StringComparison.Ordinal);
        public override readonly bool Equals(object obj) => obj is StateId other && Equals(other);
        public override readonly string ToString() => Value;
        public override readonly int GetHashCode() => IsNone ? 0 : Value.GetHashCode(StringComparison.Ordinal);
        public static bool operator ==(StateId a, StateId b) => a.Equals(b);
        public static bool operator !=(StateId a, StateId b) => !a.Equals(b);

        public static implicit operator string(StateId id) => id.Value;
        public static implicit operator StateId(string value) => new(value);
    }
}
