//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\StringIdGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using DVG.Core;
using System;
using System.Runtime.Serialization;

namespace DVG.SkyPirates.Shared.Ids
{
    [Serializable]
    [DataContract]
    partial struct TileId : IId, IEquatable<TileId>, IComparable<TileId>
    {
        [DataMember(Order = 0)]
        public string Value { get; set; }
        private const string NoneValue = "None";
        public static readonly TileId None = new TileId(NoneValue);

        public TileId(string value)
        {
            Value = value;
        }

        [IgnoreDataMember]
        public readonly bool IsNone => string.IsNullOrEmpty(Value) || Value == NoneValue;
        public readonly bool Equals(TileId other) => Value == other.Value || (IsNone && other.IsNone);
        public readonly int CompareTo(TileId other) => Equals(other) ? 0 : string.Compare(Value, other.Value);
        public override readonly bool Equals(object obj) => obj is TileId other && Equals(other);
        public override readonly string ToString() => Value;
        public override readonly int GetHashCode() => IsNone ? 0 : Value.GetHashCode();
        public static bool operator ==(TileId a, TileId b) => a.Value == b.Value || (a.IsNone && b.IsNone);
        public static bool operator !=(TileId a, TileId b) => !(a == b);

        public static implicit operator string(TileId id) => id.Value;
    }
}
