//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\StringIdConstantsGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DVG.SkyPirates.Shared.Ids
{
    partial struct TileId
    {
        public static partial class Constants
        {
            public static readonly TileId Land1 = new TileId("Land1");
            public static readonly TileId Land2 = new TileId("Land2");
            public static readonly TileId Land3 = new TileId("Land3");
            public static readonly TileId Land4 = new TileId("Land4");
            public static readonly TileId Land5 = new TileId("Land5");
            public static readonly TileId Air = new TileId("Air");

            private static readonly TileId[] _allIds = new TileId[]
            {
                new TileId("Land1"),
                new TileId("Land2"),
                new TileId("Land3"),
                new TileId("Land4"),
                new TileId("Land5"),
                new TileId("Air"),
            };
            public static ReadOnlySpan<TileId> AllIds => _allIds;
        }
    }
}
