//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\StringIdConstantsGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DVG.SkyPirates.Shared.Ids
{
    partial struct TreeId
    {
        public static partial class Constants
        {
            public static readonly TreeId Tree_01_Fall = new TreeId("Tree_01_Fall");
            public static readonly TreeId Tree_01_Spring = new TreeId("Tree_01_Spring");
            public static readonly TreeId Tree_01_Winter = new TreeId("Tree_01_Winter");
            public static readonly TreeId Tree_02_Fall = new TreeId("Tree_02_Fall");
            public static readonly TreeId Tree_02_Spring = new TreeId("Tree_02_Spring");
            public static readonly TreeId Tree_02_Winter = new TreeId("Tree_02_Winter");
            public static readonly TreeId Tree_03_Fall = new TreeId("Tree_03_Fall");
            public static readonly TreeId Tree_03_Spring = new TreeId("Tree_03_Spring");
            public static readonly TreeId Tree_03_Winter = new TreeId("Tree_03_Winter");
            public static readonly TreeId Tree_04_Fall = new TreeId("Tree_04_Fall");
            public static readonly TreeId Tree_04_Spring = new TreeId("Tree_04_Spring");
            public static readonly TreeId Tree_04_Winter = new TreeId("Tree_04_Winter");
            public static readonly TreeId Tree_05_Fall = new TreeId("Tree_05_Fall");
            public static readonly TreeId Tree_05_Spring = new TreeId("Tree_05_Spring");
            public static readonly TreeId Tree_05_Winter = new TreeId("Tree_05_Winter");
            public static readonly TreeId Tree_06_Fall = new TreeId("Tree_06_Fall");
            public static readonly TreeId Tree_06_Spring = new TreeId("Tree_06_Spring");
            public static readonly TreeId Tree_06_Winter = new TreeId("Tree_06_Winter");
            public static readonly TreeId Tree_07_Fall = new TreeId("Tree_07_Fall");
            public static readonly TreeId Tree_07_Spring = new TreeId("Tree_07_Spring");
            public static readonly TreeId Tree_07_Winter = new TreeId("Tree_07_Winter");
            public static readonly TreeId Tree_08_Fall = new TreeId("Tree_08_Fall");
            public static readonly TreeId Tree_08_Spring = new TreeId("Tree_08_Spring");
            public static readonly TreeId Tree_08_Winter = new TreeId("Tree_08_Winter");
            public static readonly TreeId Tree_09_Fall = new TreeId("Tree_09_Fall");
            public static readonly TreeId Tree_09_Spring = new TreeId("Tree_09_Spring");
            public static readonly TreeId Tree_09_Winter = new TreeId("Tree_09_Winter");
            public static readonly TreeId Tree_10_Fall = new TreeId("Tree_10_Fall");
            public static readonly TreeId Tree_10_Spring = new TreeId("Tree_10_Spring");
            public static readonly TreeId Tree_10_Winter = new TreeId("Tree_10_Winter");
            public static readonly TreeId Tree_11_Fall = new TreeId("Tree_11_Fall");
            public static readonly TreeId Tree_11_Spring = new TreeId("Tree_11_Spring");
            public static readonly TreeId Tree_11_Winter = new TreeId("Tree_11_Winter");
            public static readonly TreeId Tree_12_Fall = new TreeId("Tree_12_Fall");
            public static readonly TreeId Tree_12_Spring = new TreeId("Tree_12_Spring");
            public static readonly TreeId Tree_12_Winter = new TreeId("Tree_12_Winter");
            public static readonly TreeId Tree_13_Fall = new TreeId("Tree_13_Fall");
            public static readonly TreeId Tree_13_Spring = new TreeId("Tree_13_Spring");
            public static readonly TreeId Tree_13_Winter = new TreeId("Tree_13_Winter");
            public static readonly TreeId Tree_14_Fall = new TreeId("Tree_14_Fall");
            public static readonly TreeId Tree_14_Spring = new TreeId("Tree_14_Spring");
            public static readonly TreeId Tree_14_Winter = new TreeId("Tree_14_Winter");
            public static readonly TreeId Tree_15_Fall = new TreeId("Tree_15_Fall");
            public static readonly TreeId Tree_15_Spring = new TreeId("Tree_15_Spring");
            public static readonly TreeId Tree_15_Winter = new TreeId("Tree_15_Winter");
            public static readonly TreeId Tree_16_Fall = new TreeId("Tree_16_Fall");
            public static readonly TreeId Tree_16_Spring = new TreeId("Tree_16_Spring");
            public static readonly TreeId Tree_16_Winter = new TreeId("Tree_16_Winter");
            public static readonly TreeId Tree_17_Fall = new TreeId("Tree_17_Fall");
            public static readonly TreeId Tree_17_Spring = new TreeId("Tree_17_Spring");
            public static readonly TreeId Tree_17_Winter = new TreeId("Tree_17_Winter");
            public static readonly TreeId Tree_18_Fall = new TreeId("Tree_18_Fall");
            public static readonly TreeId Tree_18_Spring = new TreeId("Tree_18_Spring");
            public static readonly TreeId Tree_18_Winter = new TreeId("Tree_18_Winter");
            public static readonly TreeId Tree_19_Fall = new TreeId("Tree_19_Fall");
            public static readonly TreeId Tree_19_Spring = new TreeId("Tree_19_Spring");
            public static readonly TreeId Tree_19_Winter = new TreeId("Tree_19_Winter");
            public static readonly TreeId Tree_20_Fall = new TreeId("Tree_20_Fall");
            public static readonly TreeId Tree_20_Spring = new TreeId("Tree_20_Spring");
            public static readonly TreeId Tree_20_Winter = new TreeId("Tree_20_Winter");
            public static readonly TreeId Tree_21_Fall = new TreeId("Tree_21_Fall");
            public static readonly TreeId Tree_21_Spring = new TreeId("Tree_21_Spring");
            public static readonly TreeId Tree_21_Winter = new TreeId("Tree_21_Winter");
            public static readonly TreeId Tree_22_Fall = new TreeId("Tree_22_Fall");
            public static readonly TreeId Tree_22_Spring = new TreeId("Tree_22_Spring");
            public static readonly TreeId Tree_22_Winter = new TreeId("Tree_22_Winter");
            public static readonly TreeId Tree_23_Fall = new TreeId("Tree_23_Fall");
            public static readonly TreeId Tree_23_Spring = new TreeId("Tree_23_Spring");
            public static readonly TreeId Tree_23_Winter = new TreeId("Tree_23_Winter");
            public static readonly TreeId Tree_24_Fall = new TreeId("Tree_24_Fall");
            public static readonly TreeId Tree_24_Spring = new TreeId("Tree_24_Spring");
            public static readonly TreeId Tree_24_Winter = new TreeId("Tree_24_Winter");
            public static readonly TreeId Tree_25_Fall = new TreeId("Tree_25_Fall");
            public static readonly TreeId Tree_25_Spring = new TreeId("Tree_25_Spring");
            public static readonly TreeId Tree_25_Winter = new TreeId("Tree_25_Winter");
            public static readonly TreeId Tree_26_Fall = new TreeId("Tree_26_Fall");
            public static readonly TreeId Tree_26_Spring = new TreeId("Tree_26_Spring");
            public static readonly TreeId Tree_26_Winter = new TreeId("Tree_26_Winter");
            public static readonly TreeId Tree_27_Fall = new TreeId("Tree_27_Fall");
            public static readonly TreeId Tree_27_Spring = new TreeId("Tree_27_Spring");
            public static readonly TreeId Tree_27_Winter = new TreeId("Tree_27_Winter");
            public static readonly TreeId Tree_28_Fall = new TreeId("Tree_28_Fall");
            public static readonly TreeId Tree_28_Spring = new TreeId("Tree_28_Spring");
            public static readonly TreeId Tree_28_Winter = new TreeId("Tree_28_Winter");
            public static readonly TreeId Tree_29_Fall = new TreeId("Tree_29_Fall");
            public static readonly TreeId Tree_29_Spring = new TreeId("Tree_29_Spring");
            public static readonly TreeId Tree_29_Winter = new TreeId("Tree_29_Winter");
            public static readonly TreeId Tree_30_Fall = new TreeId("Tree_30_Fall");
            public static readonly TreeId Tree_30_Spring = new TreeId("Tree_30_Spring");
            public static readonly TreeId Tree_30_Winter = new TreeId("Tree_30_Winter");
            public static readonly TreeId Tree_31_Fall = new TreeId("Tree_31_Fall");
            public static readonly TreeId Tree_31_Spring = new TreeId("Tree_31_Spring");
            public static readonly TreeId Tree_31_Winter = new TreeId("Tree_31_Winter");
            public static readonly TreeId Tree_32_Fall = new TreeId("Tree_32_Fall");
            public static readonly TreeId Tree_32_Spring = new TreeId("Tree_32_Spring");
            public static readonly TreeId Tree_32_Winter = new TreeId("Tree_32_Winter");
            public static readonly TreeId Tree_33_Fall = new TreeId("Tree_33_Fall");
            public static readonly TreeId Tree_33_Spring = new TreeId("Tree_33_Spring");
            public static readonly TreeId Tree_33_Winter = new TreeId("Tree_33_Winter");
            public static readonly TreeId Tree_34_Fall = new TreeId("Tree_34_Fall");
            public static readonly TreeId Tree_34_Spring = new TreeId("Tree_34_Spring");
            public static readonly TreeId Tree_34_Winter = new TreeId("Tree_34_Winter");
            public static readonly TreeId Tree_35_Fall = new TreeId("Tree_35_Fall");
            public static readonly TreeId Tree_35_Spring = new TreeId("Tree_35_Spring");
            public static readonly TreeId Tree_35_Winter = new TreeId("Tree_35_Winter");
            public static readonly TreeId Tree_36_Fall = new TreeId("Tree_36_Fall");
            public static readonly TreeId Tree_36_Spring = new TreeId("Tree_36_Spring");
            public static readonly TreeId Tree_36_Winter = new TreeId("Tree_36_Winter");
            public static readonly TreeId Tree_37_Fall = new TreeId("Tree_37_Fall");
            public static readonly TreeId Tree_37_Spring = new TreeId("Tree_37_Spring");
            public static readonly TreeId Tree_37_Winter = new TreeId("Tree_37_Winter");
            public static readonly TreeId TreeTrunk_01 = new TreeId("TreeTrunk_01");
            public static readonly TreeId TreeTrunk_02 = new TreeId("TreeTrunk_02");
            public static readonly TreeId TreeTrunk_03 = new TreeId("TreeTrunk_03");
            public static readonly TreeId TreeTrunk_04 = new TreeId("TreeTrunk_04");
            public static readonly TreeId TreeTrunk_05 = new TreeId("TreeTrunk_05");
            public static readonly TreeId TreeTrunk_06 = new TreeId("TreeTrunk_06");
            public static readonly TreeId TreeTrunk_07 = new TreeId("TreeTrunk_07");
            public static readonly TreeId TreeTrunk_08 = new TreeId("TreeTrunk_08");
            public static readonly TreeId TreeTrunk_09 = new TreeId("TreeTrunk_09");
            public static readonly TreeId TreeTrunk_10 = new TreeId("TreeTrunk_10");
            public static readonly TreeId TreeTrunk_11 = new TreeId("TreeTrunk_11");
            public static readonly TreeId TreeTrunk_12 = new TreeId("TreeTrunk_12");
            public static readonly TreeId TreeTrunk_13 = new TreeId("TreeTrunk_13");
            public static readonly TreeId TreeTrunk_14 = new TreeId("TreeTrunk_14");
            public static readonly TreeId TreeTrunk_15 = new TreeId("TreeTrunk_15");
            public static readonly TreeId TreeTrunk_16 = new TreeId("TreeTrunk_16");
            public static readonly TreeId TreeTrunk_17 = new TreeId("TreeTrunk_17");
            public static readonly TreeId TreeTrunk_18 = new TreeId("TreeTrunk_18");
            public static readonly TreeId TreeTrunk_19 = new TreeId("TreeTrunk_19");
            public static readonly TreeId TreeTrunk_20 = new TreeId("TreeTrunk_20");
            public static readonly TreeId TreeTrunk_21 = new TreeId("TreeTrunk_21");
            public static readonly TreeId TreeTrunk_22 = new TreeId("TreeTrunk_22");
            public static readonly TreeId TreeTrunk_23 = new TreeId("TreeTrunk_23");
            public static readonly TreeId TreeTrunk_24 = new TreeId("TreeTrunk_24");
            public static readonly TreeId TreeTrunk_25 = new TreeId("TreeTrunk_25");
            public static readonly TreeId TreeTrunk_26 = new TreeId("TreeTrunk_26");
            public static readonly TreeId TreeTrunk_27 = new TreeId("TreeTrunk_27");
            public static readonly TreeId TreeTrunk_28 = new TreeId("TreeTrunk_28");
            public static readonly TreeId TreeTrunk_29 = new TreeId("TreeTrunk_29");
            public static readonly TreeId TreeTrunk_30 = new TreeId("TreeTrunk_30");
            public static readonly TreeId TreeTrunk_31 = new TreeId("TreeTrunk_31");
            public static readonly TreeId TreeTrunk_32 = new TreeId("TreeTrunk_32");
            public static readonly TreeId TreeTrunk_33 = new TreeId("TreeTrunk_33");
            public static readonly TreeId TreeTrunk_34 = new TreeId("TreeTrunk_34");
            public static readonly TreeId TreeTrunk_35 = new TreeId("TreeTrunk_35");
            public static readonly TreeId TreeTrunk_36 = new TreeId("TreeTrunk_36");
            public static readonly TreeId TreeTrunk_37 = new TreeId("TreeTrunk_37");
            public static readonly TreeId TreeTrunk_38 = new TreeId("TreeTrunk_38");
            public static readonly TreeId TreeTrunk_39 = new TreeId("TreeTrunk_39");
            public static readonly TreeId TreeTrunk_40 = new TreeId("TreeTrunk_40");
            public static readonly TreeId TreeTrunk_41 = new TreeId("TreeTrunk_41");
            public static readonly TreeId TreeTrunk_42 = new TreeId("TreeTrunk_42");
            public static readonly TreeId TreeTrunk_43 = new TreeId("TreeTrunk_43");
            public static readonly TreeId TreeTrunk_44 = new TreeId("TreeTrunk_44");
            public static readonly TreeId TreeTrunk_45 = new TreeId("TreeTrunk_45");
            public static readonly TreeId TreeTrunk_46 = new TreeId("TreeTrunk_46");
            public static readonly TreeId TreeTrunk_47 = new TreeId("TreeTrunk_47");
            public static readonly TreeId TreeTrunk_48 = new TreeId("TreeTrunk_48");
            public static readonly TreeId TreeTrunk_49 = new TreeId("TreeTrunk_49");
            public static readonly TreeId TreeTrunk_50 = new TreeId("TreeTrunk_50");
            public static readonly TreeId TreeTrunk_51 = new TreeId("TreeTrunk_51");
            public static readonly TreeId TreeTrunk_52 = new TreeId("TreeTrunk_52");
            public static readonly TreeId TreeTrunk_53 = new TreeId("TreeTrunk_53");
            public static readonly TreeId TreeTrunk_54 = new TreeId("TreeTrunk_54");
            public static readonly TreeId TreeTrunk_55 = new TreeId("TreeTrunk_55");
            public static readonly TreeId TreeTrunk_56 = new TreeId("TreeTrunk_56");

            private static readonly TreeId[] _allIds = new TreeId[]
            {
                new TreeId("Tree_01_Fall"),
                new TreeId("Tree_01_Spring"),
                new TreeId("Tree_01_Winter"),
                new TreeId("Tree_02_Fall"),
                new TreeId("Tree_02_Spring"),
                new TreeId("Tree_02_Winter"),
                new TreeId("Tree_03_Fall"),
                new TreeId("Tree_03_Spring"),
                new TreeId("Tree_03_Winter"),
                new TreeId("Tree_04_Fall"),
                new TreeId("Tree_04_Spring"),
                new TreeId("Tree_04_Winter"),
                new TreeId("Tree_05_Fall"),
                new TreeId("Tree_05_Spring"),
                new TreeId("Tree_05_Winter"),
                new TreeId("Tree_06_Fall"),
                new TreeId("Tree_06_Spring"),
                new TreeId("Tree_06_Winter"),
                new TreeId("Tree_07_Fall"),
                new TreeId("Tree_07_Spring"),
                new TreeId("Tree_07_Winter"),
                new TreeId("Tree_08_Fall"),
                new TreeId("Tree_08_Spring"),
                new TreeId("Tree_08_Winter"),
                new TreeId("Tree_09_Fall"),
                new TreeId("Tree_09_Spring"),
                new TreeId("Tree_09_Winter"),
                new TreeId("Tree_10_Fall"),
                new TreeId("Tree_10_Spring"),
                new TreeId("Tree_10_Winter"),
                new TreeId("Tree_11_Fall"),
                new TreeId("Tree_11_Spring"),
                new TreeId("Tree_11_Winter"),
                new TreeId("Tree_12_Fall"),
                new TreeId("Tree_12_Spring"),
                new TreeId("Tree_12_Winter"),
                new TreeId("Tree_13_Fall"),
                new TreeId("Tree_13_Spring"),
                new TreeId("Tree_13_Winter"),
                new TreeId("Tree_14_Fall"),
                new TreeId("Tree_14_Spring"),
                new TreeId("Tree_14_Winter"),
                new TreeId("Tree_15_Fall"),
                new TreeId("Tree_15_Spring"),
                new TreeId("Tree_15_Winter"),
                new TreeId("Tree_16_Fall"),
                new TreeId("Tree_16_Spring"),
                new TreeId("Tree_16_Winter"),
                new TreeId("Tree_17_Fall"),
                new TreeId("Tree_17_Spring"),
                new TreeId("Tree_17_Winter"),
                new TreeId("Tree_18_Fall"),
                new TreeId("Tree_18_Spring"),
                new TreeId("Tree_18_Winter"),
                new TreeId("Tree_19_Fall"),
                new TreeId("Tree_19_Spring"),
                new TreeId("Tree_19_Winter"),
                new TreeId("Tree_20_Fall"),
                new TreeId("Tree_20_Spring"),
                new TreeId("Tree_20_Winter"),
                new TreeId("Tree_21_Fall"),
                new TreeId("Tree_21_Spring"),
                new TreeId("Tree_21_Winter"),
                new TreeId("Tree_22_Fall"),
                new TreeId("Tree_22_Spring"),
                new TreeId("Tree_22_Winter"),
                new TreeId("Tree_23_Fall"),
                new TreeId("Tree_23_Spring"),
                new TreeId("Tree_23_Winter"),
                new TreeId("Tree_24_Fall"),
                new TreeId("Tree_24_Spring"),
                new TreeId("Tree_24_Winter"),
                new TreeId("Tree_25_Fall"),
                new TreeId("Tree_25_Spring"),
                new TreeId("Tree_25_Winter"),
                new TreeId("Tree_26_Fall"),
                new TreeId("Tree_26_Spring"),
                new TreeId("Tree_26_Winter"),
                new TreeId("Tree_27_Fall"),
                new TreeId("Tree_27_Spring"),
                new TreeId("Tree_27_Winter"),
                new TreeId("Tree_28_Fall"),
                new TreeId("Tree_28_Spring"),
                new TreeId("Tree_28_Winter"),
                new TreeId("Tree_29_Fall"),
                new TreeId("Tree_29_Spring"),
                new TreeId("Tree_29_Winter"),
                new TreeId("Tree_30_Fall"),
                new TreeId("Tree_30_Spring"),
                new TreeId("Tree_30_Winter"),
                new TreeId("Tree_31_Fall"),
                new TreeId("Tree_31_Spring"),
                new TreeId("Tree_31_Winter"),
                new TreeId("Tree_32_Fall"),
                new TreeId("Tree_32_Spring"),
                new TreeId("Tree_32_Winter"),
                new TreeId("Tree_33_Fall"),
                new TreeId("Tree_33_Spring"),
                new TreeId("Tree_33_Winter"),
                new TreeId("Tree_34_Fall"),
                new TreeId("Tree_34_Spring"),
                new TreeId("Tree_34_Winter"),
                new TreeId("Tree_35_Fall"),
                new TreeId("Tree_35_Spring"),
                new TreeId("Tree_35_Winter"),
                new TreeId("Tree_36_Fall"),
                new TreeId("Tree_36_Spring"),
                new TreeId("Tree_36_Winter"),
                new TreeId("Tree_37_Fall"),
                new TreeId("Tree_37_Spring"),
                new TreeId("Tree_37_Winter"),
                new TreeId("TreeTrunk_01"),
                new TreeId("TreeTrunk_02"),
                new TreeId("TreeTrunk_03"),
                new TreeId("TreeTrunk_04"),
                new TreeId("TreeTrunk_05"),
                new TreeId("TreeTrunk_06"),
                new TreeId("TreeTrunk_07"),
                new TreeId("TreeTrunk_08"),
                new TreeId("TreeTrunk_09"),
                new TreeId("TreeTrunk_10"),
                new TreeId("TreeTrunk_11"),
                new TreeId("TreeTrunk_12"),
                new TreeId("TreeTrunk_13"),
                new TreeId("TreeTrunk_14"),
                new TreeId("TreeTrunk_15"),
                new TreeId("TreeTrunk_16"),
                new TreeId("TreeTrunk_17"),
                new TreeId("TreeTrunk_18"),
                new TreeId("TreeTrunk_19"),
                new TreeId("TreeTrunk_20"),
                new TreeId("TreeTrunk_21"),
                new TreeId("TreeTrunk_22"),
                new TreeId("TreeTrunk_23"),
                new TreeId("TreeTrunk_24"),
                new TreeId("TreeTrunk_25"),
                new TreeId("TreeTrunk_26"),
                new TreeId("TreeTrunk_27"),
                new TreeId("TreeTrunk_28"),
                new TreeId("TreeTrunk_29"),
                new TreeId("TreeTrunk_30"),
                new TreeId("TreeTrunk_31"),
                new TreeId("TreeTrunk_32"),
                new TreeId("TreeTrunk_33"),
                new TreeId("TreeTrunk_34"),
                new TreeId("TreeTrunk_35"),
                new TreeId("TreeTrunk_36"),
                new TreeId("TreeTrunk_37"),
                new TreeId("TreeTrunk_38"),
                new TreeId("TreeTrunk_39"),
                new TreeId("TreeTrunk_40"),
                new TreeId("TreeTrunk_41"),
                new TreeId("TreeTrunk_42"),
                new TreeId("TreeTrunk_43"),
                new TreeId("TreeTrunk_44"),
                new TreeId("TreeTrunk_45"),
                new TreeId("TreeTrunk_46"),
                new TreeId("TreeTrunk_47"),
                new TreeId("TreeTrunk_48"),
                new TreeId("TreeTrunk_49"),
                new TreeId("TreeTrunk_50"),
                new TreeId("TreeTrunk_51"),
                new TreeId("TreeTrunk_52"),
                new TreeId("TreeTrunk_53"),
                new TreeId("TreeTrunk_54"),
                new TreeId("TreeTrunk_55"),
                new TreeId("TreeTrunk_56"),
            };
            public static ReadOnlySpan<TreeId> AllIds => _allIds;
        }
    }
}
