//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\StringIdGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using DVG.Ids;
using System;
using System.Runtime.Serialization;

namespace DVG.SkyPirates.Shared.Ids
{
    [Serializable]
    [DataContract]
    partial struct UnitId : IId, IEquatable<UnitId>, IComparable<UnitId>
    {
        [DataMember(Order = 0)]
        public string Value;
        string IId.Value => Value;
        private const string NoneValue = "None";
        public static readonly UnitId None = new UnitId(NoneValue);

        public UnitId(string value)
        {
            Value = value;
        }

        [IgnoreDataMember]
        public readonly bool IsNone => string.IsNullOrWhiteSpace(Value) || string.Equals(Value, NoneValue, StringComparison.Ordinal);
        public readonly bool Equals(UnitId other) => (IsNone && other.IsNone) || string.Equals(Value, other.Value, StringComparison.Ordinal);
        public readonly int CompareTo(UnitId other) => Equals(other) ? 0 : string.Compare(Value, other.Value, StringComparison.Ordinal);
        public override readonly bool Equals(object obj) => obj is UnitId other && Equals(other);
        public override readonly string ToString() => Value;
        public override readonly int GetHashCode() => IsNone ? 0 : Value.GetHashCode(StringComparison.Ordinal);
        public static bool operator ==(UnitId a, UnitId b) => a.Equals(b);
        public static bool operator !=(UnitId a, UnitId b) => !a.Equals(b);

        public static implicit operator string(UnitId id) => id.Value;
        public static implicit operator UnitId(string value) => new(value);
    }
}
