//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\WorldDataGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

using DVG.SkyPirates.Shared.Components;
using DVG.SkyPirates.Shared.Ids;
using DVG.SkyPirates.Shared.Components.Data;

namespace DVG.SkyPirates.Shared.Data
{
    [Serializable]
    [DataContract]
    public sealed class WorldData
    {

        [DataMember(Order = 0)]
        public Dictionary<int, Alive> Alive;
        [DataMember(Order = 1)]
        public Dictionary<int, AutoHeal> AutoHeal;
        [DataMember(Order = 2)]
        public Dictionary<int, BehaviourState> Behaviour;
        [DataMember(Order = 3)]
        public Dictionary<int, BehaviourConfig> BehaviourConfig;
        [DataMember(Order = 4)]
        public Dictionary<int, CachePosition> CachePosition;
        [DataMember(Order = 5)]
        public Dictionary<int, CactusId> CactusId;
        [DataMember(Order = 6)]
        public Dictionary<int, CircleShape> CircleShape;
        [DataMember(Order = 7)]
        public Dictionary<int, Damage> Damage;
        [DataMember(Order = 8)]
        public Dictionary<int, Destination> Destination;
        [DataMember(Order = 9)]
        public Dictionary<int, Direction> Direction;
        [DataMember(Order = 10)]
        public Dictionary<int, Fixation> Fixation;
        [DataMember(Order = 11)]
        public Dictionary<int, Health> Health;
        [DataMember(Order = 12)]
        public Dictionary<int, HexMap> HexMap;
        [DataMember(Order = 13)]
        public Dictionary<int, ImpactDistance> ImpactDistance;
        [DataMember(Order = 14)]
        public Dictionary<int, Level> Level;
        [DataMember(Order = 15)]
        public Dictionary<int, MaxHealth> MaxHealth;
        [DataMember(Order = 16)]
        public Dictionary<int, MoveSpeed> MoveSpeed;
        [DataMember(Order = 17)]
        public Dictionary<int, Position> Position;
        [DataMember(Order = 18)]
        public Dictionary<int, RecivedDamage> RecivedDamage;
        [DataMember(Order = 19)]
        public Dictionary<int, RockId> RockId;
        [DataMember(Order = 20)]
        public Dictionary<int, Rotation> Rotation;
        [DataMember(Order = 21)]
        public Dictionary<int, Separation> Separation;
        [DataMember(Order = 22)]
        public Dictionary<int, Squad> Squad;
        [DataMember(Order = 23)]
        public Dictionary<int, Target> Target;
        [DataMember(Order = 24)]
        public Dictionary<int, Targets> Targets;
        [DataMember(Order = 25)]
        public Dictionary<int, TargetSearchData> TargetSearchData;
        [DataMember(Order = 26)]
        public Dictionary<int, Team> Team;
        [DataMember(Order = 27)]
        public Dictionary<int, TreeId> TreeId;
        [DataMember(Order = 28)]
        public Dictionary<int, UnitId> UnitId;

        public WorldData()
        {

            Alive = new();
            AutoHeal = new();
            Behaviour = new();
            BehaviourConfig = new();
            CachePosition = new();
            CactusId = new();
            CircleShape = new();
            Damage = new();
            Destination = new();
            Direction = new();
            Fixation = new();
            Health = new();
            HexMap = new();
            ImpactDistance = new();
            Level = new();
            MaxHealth = new();
            MoveSpeed = new();
            Position = new();
            RecivedDamage = new();
            RockId = new();
            Rotation = new();
            Separation = new();
            Squad = new();
            Target = new();
            Targets = new();
            TargetSearchData = new();
            Team = new();
            TreeId = new();
            UnitId = new();
        }

        public Dictionary<int, T> Get<T>()
            where T : struct
        {

            if (typeof(T) == typeof(Alive))
                return Alive as Dictionary<int, T>;
            if (typeof(T) == typeof(AutoHeal))
                return AutoHeal as Dictionary<int, T>;
            if (typeof(T) == typeof(BehaviourState))
                return Behaviour as Dictionary<int, T>;
            if (typeof(T) == typeof(BehaviourConfig))
                return BehaviourConfig as Dictionary<int, T>;
            if (typeof(T) == typeof(CachePosition))
                return CachePosition as Dictionary<int, T>;
            if (typeof(T) == typeof(CactusId))
                return CactusId as Dictionary<int, T>;
            if (typeof(T) == typeof(CircleShape))
                return CircleShape as Dictionary<int, T>;
            if (typeof(T) == typeof(Damage))
                return Damage as Dictionary<int, T>;
            if (typeof(T) == typeof(Destination))
                return Destination as Dictionary<int, T>;
            if (typeof(T) == typeof(Direction))
                return Direction as Dictionary<int, T>;
            if (typeof(T) == typeof(Fixation))
                return Fixation as Dictionary<int, T>;
            if (typeof(T) == typeof(Health))
                return Health as Dictionary<int, T>;
            if (typeof(T) == typeof(HexMap))
                return HexMap as Dictionary<int, T>;
            if (typeof(T) == typeof(ImpactDistance))
                return ImpactDistance as Dictionary<int, T>;
            if (typeof(T) == typeof(Level))
                return Level as Dictionary<int, T>;
            if (typeof(T) == typeof(MaxHealth))
                return MaxHealth as Dictionary<int, T>;
            if (typeof(T) == typeof(MoveSpeed))
                return MoveSpeed as Dictionary<int, T>;
            if (typeof(T) == typeof(Position))
                return Position as Dictionary<int, T>;
            if (typeof(T) == typeof(RecivedDamage))
                return RecivedDamage as Dictionary<int, T>;
            if (typeof(T) == typeof(RockId))
                return RockId as Dictionary<int, T>;
            if (typeof(T) == typeof(Rotation))
                return Rotation as Dictionary<int, T>;
            if (typeof(T) == typeof(Separation))
                return Separation as Dictionary<int, T>;
            if (typeof(T) == typeof(Squad))
                return Squad as Dictionary<int, T>;
            if (typeof(T) == typeof(Target))
                return Target as Dictionary<int, T>;
            if (typeof(T) == typeof(Targets))
                return Targets as Dictionary<int, T>;
            if (typeof(T) == typeof(TargetSearchData))
                return TargetSearchData as Dictionary<int, T>;
            if (typeof(T) == typeof(Team))
                return Team as Dictionary<int, T>;
            if (typeof(T) == typeof(TreeId))
                return TreeId as Dictionary<int, T>;
            if (typeof(T) == typeof(UnitId))
                return UnitId as Dictionary<int, T>;

            throw new NotSupportedException(typeof(T).Name);
        }

        public void Set<T>(Dictionary<int, T> data)
            where T : struct
        {

            if (typeof(T) == typeof(Alive))
            {
                Alive = data as Dictionary<int, Alive>;
                return;
            }
            if (typeof(T) == typeof(AutoHeal))
            {
                AutoHeal = data as Dictionary<int, AutoHeal>;
                return;
            }
            if (typeof(T) == typeof(BehaviourState))
            {
                Behaviour = data as Dictionary<int, BehaviourState>;
                return;
            }
            if (typeof(T) == typeof(BehaviourConfig))
            {
                BehaviourConfig = data as Dictionary<int, BehaviourConfig>;
                return;
            }
            if (typeof(T) == typeof(CachePosition))
            {
                CachePosition = data as Dictionary<int, CachePosition>;
                return;
            }
            if (typeof(T) == typeof(CactusId))
            {
                CactusId = data as Dictionary<int, CactusId>;
                return;
            }
            if (typeof(T) == typeof(CircleShape))
            {
                CircleShape = data as Dictionary<int, CircleShape>;
                return;
            }
            if (typeof(T) == typeof(Damage))
            {
                Damage = data as Dictionary<int, Damage>;
                return;
            }
            if (typeof(T) == typeof(Destination))
            {
                Destination = data as Dictionary<int, Destination>;
                return;
            }
            if (typeof(T) == typeof(Direction))
            {
                Direction = data as Dictionary<int, Direction>;
                return;
            }
            if (typeof(T) == typeof(Fixation))
            {
                Fixation = data as Dictionary<int, Fixation>;
                return;
            }
            if (typeof(T) == typeof(Health))
            {
                Health = data as Dictionary<int, Health>;
                return;
            }
            if (typeof(T) == typeof(HexMap))
            {
                HexMap = data as Dictionary<int, HexMap>;
                return;
            }
            if (typeof(T) == typeof(ImpactDistance))
            {
                ImpactDistance = data as Dictionary<int, ImpactDistance>;
                return;
            }
            if (typeof(T) == typeof(Level))
            {
                Level = data as Dictionary<int, Level>;
                return;
            }
            if (typeof(T) == typeof(MaxHealth))
            {
                MaxHealth = data as Dictionary<int, MaxHealth>;
                return;
            }
            if (typeof(T) == typeof(MoveSpeed))
            {
                MoveSpeed = data as Dictionary<int, MoveSpeed>;
                return;
            }
            if (typeof(T) == typeof(Position))
            {
                Position = data as Dictionary<int, Position>;
                return;
            }
            if (typeof(T) == typeof(RecivedDamage))
            {
                RecivedDamage = data as Dictionary<int, RecivedDamage>;
                return;
            }
            if (typeof(T) == typeof(RockId))
            {
                RockId = data as Dictionary<int, RockId>;
                return;
            }
            if (typeof(T) == typeof(Rotation))
            {
                Rotation = data as Dictionary<int, Rotation>;
                return;
            }
            if (typeof(T) == typeof(Separation))
            {
                Separation = data as Dictionary<int, Separation>;
                return;
            }
            if (typeof(T) == typeof(Squad))
            {
                Squad = data as Dictionary<int, Squad>;
                return;
            }
            if (typeof(T) == typeof(Target))
            {
                Target = data as Dictionary<int, Target>;
                return;
            }
            if (typeof(T) == typeof(Targets))
            {
                Targets = data as Dictionary<int, Targets>;
                return;
            }
            if (typeof(T) == typeof(TargetSearchData))
            {
                TargetSearchData = data as Dictionary<int, TargetSearchData>;
                return;
            }
            if (typeof(T) == typeof(Team))
            {
                Team = data as Dictionary<int, Team>;
                return;
            }
            if (typeof(T) == typeof(TreeId))
            {
                TreeId = data as Dictionary<int, TreeId>;
                return;
            }
            if (typeof(T) == typeof(UnitId))
            {
                UnitId = data as Dictionary<int, UnitId>;
                return;
            }

            throw new NotSupportedException(typeof(T).Name);
        }
    }
}
