//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\WorldDataGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

using DVG.SkyPirates.Shared.Ids;
using DVG.SkyPirates.Shared.Components;
using DVG.SkyPirates.Shared.Components.Data;

namespace DVG.SkyPirates.Shared.Data
{
    [Serializable]
    [DataContract]
    public sealed class WorldData
    {

        [DataMember(Order = 0)]
        public Dictionary<int, RockId> RockIds;
        [DataMember(Order = 1)]
        public Dictionary<int, TreeId> TreeIds;
        [DataMember(Order = 2)]
        public Dictionary<int, UnitId> UnitIds;
        [DataMember(Order = 3)]
        public Dictionary<int, Alive> Alives;
        [DataMember(Order = 4)]
        public Dictionary<int, AutoHeal> AutoHeals;
        [DataMember(Order = 5)]
        public Dictionary<int, Behaviour> Behaviours;
        [DataMember(Order = 6)]
        public Dictionary<int, BehaviourConfig> BehaviourConfigs;
        [DataMember(Order = 7)]
        public Dictionary<int, CachePosition> CachePositions;
        [DataMember(Order = 8)]
        public Dictionary<int, Destination> Destinations;
        [DataMember(Order = 9)]
        public Dictionary<int, Direction> Directions;
        [DataMember(Order = 10)]
        public Dictionary<int, Fixation> Fixations;
        [DataMember(Order = 11)]
        public Dictionary<int, RecivedDamage> RecivedDamages;
        [DataMember(Order = 12)]
        public Dictionary<int, Separation> Separations;
        [DataMember(Order = 13)]
        public Dictionary<int, Squad> Squads;
        [DataMember(Order = 14)]
        public Dictionary<int, Target> Targets;
        [DataMember(Order = 15)]
        public Dictionary<int, TargetSearchData> TargetSearchDatas;
        [DataMember(Order = 16)]
        public Dictionary<int, CircleShape> CircleShapes;
        [DataMember(Order = 17)]
        public Dictionary<int, Damage> Damages;
        [DataMember(Order = 18)]
        public Dictionary<int, Health> Healths;
        [DataMember(Order = 19)]
        public Dictionary<int, HexMap> HexMaps;
        [DataMember(Order = 20)]
        public Dictionary<int, ImpactDistance> ImpactDistances;
        [DataMember(Order = 21)]
        public Dictionary<int, Level> Levels;
        [DataMember(Order = 22)]
        public Dictionary<int, MaxHealth> MaxHealths;
        [DataMember(Order = 23)]
        public Dictionary<int, MoveSpeed> MoveSpeeds;
        [DataMember(Order = 24)]
        public Dictionary<int, Position> Positions;
        [DataMember(Order = 25)]
        public Dictionary<int, Rotation> Rotations;
        [DataMember(Order = 26)]
        public Dictionary<int, Team> Teams;

        public WorldData()
        {

            RockIds = new();
            TreeIds = new();
            UnitIds = new();
            Alives = new();
            AutoHeals = new();
            Behaviours = new();
            BehaviourConfigs = new();
            CachePositions = new();
            Destinations = new();
            Directions = new();
            Fixations = new();
            RecivedDamages = new();
            Separations = new();
            Squads = new();
            Targets = new();
            TargetSearchDatas = new();
            CircleShapes = new();
            Damages = new();
            Healths = new();
            HexMaps = new();
            ImpactDistances = new();
            Levels = new();
            MaxHealths = new();
            MoveSpeeds = new();
            Positions = new();
            Rotations = new();
            Teams = new();
        }

        public Dictionary<int, T> Get<T>()
            where T : struct
        {

            if (typeof(T) == typeof(RockId))
                return RockIds as Dictionary<int, T>;
            if (typeof(T) == typeof(TreeId))
                return TreeIds as Dictionary<int, T>;
            if (typeof(T) == typeof(UnitId))
                return UnitIds as Dictionary<int, T>;
            if (typeof(T) == typeof(Alive))
                return Alives as Dictionary<int, T>;
            if (typeof(T) == typeof(AutoHeal))
                return AutoHeals as Dictionary<int, T>;
            if (typeof(T) == typeof(Behaviour))
                return Behaviours as Dictionary<int, T>;
            if (typeof(T) == typeof(BehaviourConfig))
                return BehaviourConfigs as Dictionary<int, T>;
            if (typeof(T) == typeof(CachePosition))
                return CachePositions as Dictionary<int, T>;
            if (typeof(T) == typeof(Destination))
                return Destinations as Dictionary<int, T>;
            if (typeof(T) == typeof(Direction))
                return Directions as Dictionary<int, T>;
            if (typeof(T) == typeof(Fixation))
                return Fixations as Dictionary<int, T>;
            if (typeof(T) == typeof(RecivedDamage))
                return RecivedDamages as Dictionary<int, T>;
            if (typeof(T) == typeof(Separation))
                return Separations as Dictionary<int, T>;
            if (typeof(T) == typeof(Squad))
                return Squads as Dictionary<int, T>;
            if (typeof(T) == typeof(Target))
                return Targets as Dictionary<int, T>;
            if (typeof(T) == typeof(TargetSearchData))
                return TargetSearchDatas as Dictionary<int, T>;
            if (typeof(T) == typeof(CircleShape))
                return CircleShapes as Dictionary<int, T>;
            if (typeof(T) == typeof(Damage))
                return Damages as Dictionary<int, T>;
            if (typeof(T) == typeof(Health))
                return Healths as Dictionary<int, T>;
            if (typeof(T) == typeof(HexMap))
                return HexMaps as Dictionary<int, T>;
            if (typeof(T) == typeof(ImpactDistance))
                return ImpactDistances as Dictionary<int, T>;
            if (typeof(T) == typeof(Level))
                return Levels as Dictionary<int, T>;
            if (typeof(T) == typeof(MaxHealth))
                return MaxHealths as Dictionary<int, T>;
            if (typeof(T) == typeof(MoveSpeed))
                return MoveSpeeds as Dictionary<int, T>;
            if (typeof(T) == typeof(Position))
                return Positions as Dictionary<int, T>;
            if (typeof(T) == typeof(Rotation))
                return Rotations as Dictionary<int, T>;
            if (typeof(T) == typeof(Team))
                return Teams as Dictionary<int, T>;

            throw new NotSupportedException(typeof(T).Name);
        }

        public void Set<T>(Dictionary<int, T> data)
            where T : struct
        {

            if (typeof(T) == typeof(RockId))
            {
                RockIds = data as Dictionary<int, RockId>;
                return;
            }
            if (typeof(T) == typeof(TreeId))
            {
                TreeIds = data as Dictionary<int, TreeId>;
                return;
            }
            if (typeof(T) == typeof(UnitId))
            {
                UnitIds = data as Dictionary<int, UnitId>;
                return;
            }
            if (typeof(T) == typeof(Alive))
            {
                Alives = data as Dictionary<int, Alive>;
                return;
            }
            if (typeof(T) == typeof(AutoHeal))
            {
                AutoHeals = data as Dictionary<int, AutoHeal>;
                return;
            }
            if (typeof(T) == typeof(Behaviour))
            {
                Behaviours = data as Dictionary<int, Behaviour>;
                return;
            }
            if (typeof(T) == typeof(BehaviourConfig))
            {
                BehaviourConfigs = data as Dictionary<int, BehaviourConfig>;
                return;
            }
            if (typeof(T) == typeof(CachePosition))
            {
                CachePositions = data as Dictionary<int, CachePosition>;
                return;
            }
            if (typeof(T) == typeof(Destination))
            {
                Destinations = data as Dictionary<int, Destination>;
                return;
            }
            if (typeof(T) == typeof(Direction))
            {
                Directions = data as Dictionary<int, Direction>;
                return;
            }
            if (typeof(T) == typeof(Fixation))
            {
                Fixations = data as Dictionary<int, Fixation>;
                return;
            }
            if (typeof(T) == typeof(RecivedDamage))
            {
                RecivedDamages = data as Dictionary<int, RecivedDamage>;
                return;
            }
            if (typeof(T) == typeof(Separation))
            {
                Separations = data as Dictionary<int, Separation>;
                return;
            }
            if (typeof(T) == typeof(Squad))
            {
                Squads = data as Dictionary<int, Squad>;
                return;
            }
            if (typeof(T) == typeof(Target))
            {
                Targets = data as Dictionary<int, Target>;
                return;
            }
            if (typeof(T) == typeof(TargetSearchData))
            {
                TargetSearchDatas = data as Dictionary<int, TargetSearchData>;
                return;
            }
            if (typeof(T) == typeof(CircleShape))
            {
                CircleShapes = data as Dictionary<int, CircleShape>;
                return;
            }
            if (typeof(T) == typeof(Damage))
            {
                Damages = data as Dictionary<int, Damage>;
                return;
            }
            if (typeof(T) == typeof(Health))
            {
                Healths = data as Dictionary<int, Health>;
                return;
            }
            if (typeof(T) == typeof(HexMap))
            {
                HexMaps = data as Dictionary<int, HexMap>;
                return;
            }
            if (typeof(T) == typeof(ImpactDistance))
            {
                ImpactDistances = data as Dictionary<int, ImpactDistance>;
                return;
            }
            if (typeof(T) == typeof(Level))
            {
                Levels = data as Dictionary<int, Level>;
                return;
            }
            if (typeof(T) == typeof(MaxHealth))
            {
                MaxHealths = data as Dictionary<int, MaxHealth>;
                return;
            }
            if (typeof(T) == typeof(MoveSpeed))
            {
                MoveSpeeds = data as Dictionary<int, MoveSpeed>;
                return;
            }
            if (typeof(T) == typeof(Position))
            {
                Positions = data as Dictionary<int, Position>;
                return;
            }
            if (typeof(T) == typeof(Rotation))
            {
                Rotations = data as Dictionary<int, Rotation>;
                return;
            }
            if (typeof(T) == typeof(Team))
            {
                Teams = data as Dictionary<int, Team>;
                return;
            }

            throw new NotSupportedException(typeof(T).Name);
        }
    }
}
