//------------------------------------------------------------------------------
// <auto-generated>
//
// This code was generated by a tool.
// Path: ..\..\..\Generators\WorldDataGenerator.cs
//
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

using DVG.SkyPirates.Shared.Components.Config;
using DVG.SkyPirates.Shared.Components.Runtime;
using DVG.SkyPirates.Shared.Ids;
using DVG.Components;

namespace DVG.SkyPirates.Shared.Data
{
    [Serializable]
    [DataContract]
    public sealed class WorldData
    {

        [DataMember]
        private Dictionary<int, ActivityRange> ActivityRange;
        [DataMember]
        private Dictionary<int, AutoHeal> AutoHeal;
        [DataMember]
        private Dictionary<int, BehaviourConfig> BehaviourConfig;
        [DataMember]
        private Dictionary<int, BehaviourState> BehaviourState;
        [DataMember]
        private Dictionary<int, CactusId> CactusId;
        [DataMember]
        private Dictionary<int, ClientId> ClientId;
        [DataMember]
        private Dictionary<int, Damage> Damage;
        [DataMember]
        private Dictionary<int, Direction> Direction;
        [DataMember]
        private Dictionary<int, Disposing> Disposing;
        [DataMember]
        private Dictionary<int, Fixation> Fixation;
        [DataMember]
        private Dictionary<int, FlyDestination> FlyDestination;
        [DataMember]
        private Dictionary<int, GoodsAmount> GoodsAmount;
        [DataMember]
        private Dictionary<int, GoodsCollectorRadius> GoodsCollectorRadius;
        [DataMember]
        private Dictionary<int, GoodsDrop> GoodsDrop;
        [DataMember]
        private Dictionary<int, GoodsId> GoodsId;
        [DataMember]
        private Dictionary<int, Health> Health;
        [DataMember]
        private Dictionary<int, HexMap> HexMap;
        [DataMember]
        private Dictionary<int, ImpactDistance> ImpactDistance;
        [DataMember]
        private Dictionary<int, Level> Level;
        [DataMember]
        private Dictionary<int, MaxHealth> MaxHealth;
        [DataMember]
        private Dictionary<int, MaxSpeed> MaxSpeed;
        [DataMember]
        private Dictionary<int, Position> Position;
        [DataMember]
        private Dictionary<int, Radius> Radius;
        [DataMember]
        private Dictionary<int, RandomSeed> RandomSeed;
        [DataMember]
        private Dictionary<int, RockId> RockId;
        [DataMember]
        private Dictionary<int, Rotation> Rotation;
        [DataMember]
        private Dictionary<int, Separation> Separation;
        [DataMember]
        private Dictionary<int, Separator> Separator;
        [DataMember]
        private Dictionary<int, Squad> Squad;
        [DataMember]
        private Dictionary<int, SquadMember> SquadMember;
        [DataMember]
        private Dictionary<int, SyncId> SyncId;
        [DataMember]
        private Dictionary<int, SyncIdReserve> SyncIdReserve;
        [DataMember]
        private Dictionary<int, TargetSearchDistance> TargetSearchDistance;
        [DataMember]
        private Dictionary<int, TeamId> TeamId;
        [DataMember]
        private Dictionary<int, TreeId> TreeId;
        [DataMember]
        private Dictionary<int, UnitId> UnitId;

        public WorldData()
        {

            ActivityRange = new();
            AutoHeal = new();
            BehaviourConfig = new();
            BehaviourState = new();
            CactusId = new();
            ClientId = new();
            Damage = new();
            Direction = new();
            Disposing = new();
            Fixation = new();
            FlyDestination = new();
            GoodsAmount = new();
            GoodsCollectorRadius = new();
            GoodsDrop = new();
            GoodsId = new();
            Health = new();
            HexMap = new();
            ImpactDistance = new();
            Level = new();
            MaxHealth = new();
            MaxSpeed = new();
            Position = new();
            Radius = new();
            RandomSeed = new();
            RockId = new();
            Rotation = new();
            Separation = new();
            Separator = new();
            Squad = new();
            SquadMember = new();
            SyncId = new();
            SyncIdReserve = new();
            TargetSearchDistance = new();
            TeamId = new();
            TreeId = new();
            UnitId = new();
        }

        public Dictionary<int, T> Get<T>()
            where T : struct
        {

            if (typeof(T) == typeof(ActivityRange))
                return ActivityRange as Dictionary<int, T>;
            if (typeof(T) == typeof(AutoHeal))
                return AutoHeal as Dictionary<int, T>;
            if (typeof(T) == typeof(BehaviourConfig))
                return BehaviourConfig as Dictionary<int, T>;
            if (typeof(T) == typeof(BehaviourState))
                return BehaviourState as Dictionary<int, T>;
            if (typeof(T) == typeof(CactusId))
                return CactusId as Dictionary<int, T>;
            if (typeof(T) == typeof(ClientId))
                return ClientId as Dictionary<int, T>;
            if (typeof(T) == typeof(Damage))
                return Damage as Dictionary<int, T>;
            if (typeof(T) == typeof(Direction))
                return Direction as Dictionary<int, T>;
            if (typeof(T) == typeof(Disposing))
                return Disposing as Dictionary<int, T>;
            if (typeof(T) == typeof(Fixation))
                return Fixation as Dictionary<int, T>;
            if (typeof(T) == typeof(FlyDestination))
                return FlyDestination as Dictionary<int, T>;
            if (typeof(T) == typeof(GoodsAmount))
                return GoodsAmount as Dictionary<int, T>;
            if (typeof(T) == typeof(GoodsCollectorRadius))
                return GoodsCollectorRadius as Dictionary<int, T>;
            if (typeof(T) == typeof(GoodsDrop))
                return GoodsDrop as Dictionary<int, T>;
            if (typeof(T) == typeof(GoodsId))
                return GoodsId as Dictionary<int, T>;
            if (typeof(T) == typeof(Health))
                return Health as Dictionary<int, T>;
            if (typeof(T) == typeof(HexMap))
                return HexMap as Dictionary<int, T>;
            if (typeof(T) == typeof(ImpactDistance))
                return ImpactDistance as Dictionary<int, T>;
            if (typeof(T) == typeof(Level))
                return Level as Dictionary<int, T>;
            if (typeof(T) == typeof(MaxHealth))
                return MaxHealth as Dictionary<int, T>;
            if (typeof(T) == typeof(MaxSpeed))
                return MaxSpeed as Dictionary<int, T>;
            if (typeof(T) == typeof(Position))
                return Position as Dictionary<int, T>;
            if (typeof(T) == typeof(Radius))
                return Radius as Dictionary<int, T>;
            if (typeof(T) == typeof(RandomSeed))
                return RandomSeed as Dictionary<int, T>;
            if (typeof(T) == typeof(RockId))
                return RockId as Dictionary<int, T>;
            if (typeof(T) == typeof(Rotation))
                return Rotation as Dictionary<int, T>;
            if (typeof(T) == typeof(Separation))
                return Separation as Dictionary<int, T>;
            if (typeof(T) == typeof(Separator))
                return Separator as Dictionary<int, T>;
            if (typeof(T) == typeof(Squad))
                return Squad as Dictionary<int, T>;
            if (typeof(T) == typeof(SquadMember))
                return SquadMember as Dictionary<int, T>;
            if (typeof(T) == typeof(SyncId))
                return SyncId as Dictionary<int, T>;
            if (typeof(T) == typeof(SyncIdReserve))
                return SyncIdReserve as Dictionary<int, T>;
            if (typeof(T) == typeof(TargetSearchDistance))
                return TargetSearchDistance as Dictionary<int, T>;
            if (typeof(T) == typeof(TeamId))
                return TeamId as Dictionary<int, T>;
            if (typeof(T) == typeof(TreeId))
                return TreeId as Dictionary<int, T>;
            if (typeof(T) == typeof(UnitId))
                return UnitId as Dictionary<int, T>;

            throw new NotSupportedException(typeof(T).Name);
        }

        public void Set<T>(Dictionary<int, T> data)
            where T : struct
        {

            if (typeof(T) == typeof(ActivityRange))
            {
                ActivityRange = data as Dictionary<int, ActivityRange>;
                return;
            }
            if (typeof(T) == typeof(AutoHeal))
            {
                AutoHeal = data as Dictionary<int, AutoHeal>;
                return;
            }
            if (typeof(T) == typeof(BehaviourConfig))
            {
                BehaviourConfig = data as Dictionary<int, BehaviourConfig>;
                return;
            }
            if (typeof(T) == typeof(BehaviourState))
            {
                BehaviourState = data as Dictionary<int, BehaviourState>;
                return;
            }
            if (typeof(T) == typeof(CactusId))
            {
                CactusId = data as Dictionary<int, CactusId>;
                return;
            }
            if (typeof(T) == typeof(ClientId))
            {
                ClientId = data as Dictionary<int, ClientId>;
                return;
            }
            if (typeof(T) == typeof(Damage))
            {
                Damage = data as Dictionary<int, Damage>;
                return;
            }
            if (typeof(T) == typeof(Direction))
            {
                Direction = data as Dictionary<int, Direction>;
                return;
            }
            if (typeof(T) == typeof(Disposing))
            {
                Disposing = data as Dictionary<int, Disposing>;
                return;
            }
            if (typeof(T) == typeof(Fixation))
            {
                Fixation = data as Dictionary<int, Fixation>;
                return;
            }
            if (typeof(T) == typeof(FlyDestination))
            {
                FlyDestination = data as Dictionary<int, FlyDestination>;
                return;
            }
            if (typeof(T) == typeof(GoodsAmount))
            {
                GoodsAmount = data as Dictionary<int, GoodsAmount>;
                return;
            }
            if (typeof(T) == typeof(GoodsCollectorRadius))
            {
                GoodsCollectorRadius = data as Dictionary<int, GoodsCollectorRadius>;
                return;
            }
            if (typeof(T) == typeof(GoodsDrop))
            {
                GoodsDrop = data as Dictionary<int, GoodsDrop>;
                return;
            }
            if (typeof(T) == typeof(GoodsId))
            {
                GoodsId = data as Dictionary<int, GoodsId>;
                return;
            }
            if (typeof(T) == typeof(Health))
            {
                Health = data as Dictionary<int, Health>;
                return;
            }
            if (typeof(T) == typeof(HexMap))
            {
                HexMap = data as Dictionary<int, HexMap>;
                return;
            }
            if (typeof(T) == typeof(ImpactDistance))
            {
                ImpactDistance = data as Dictionary<int, ImpactDistance>;
                return;
            }
            if (typeof(T) == typeof(Level))
            {
                Level = data as Dictionary<int, Level>;
                return;
            }
            if (typeof(T) == typeof(MaxHealth))
            {
                MaxHealth = data as Dictionary<int, MaxHealth>;
                return;
            }
            if (typeof(T) == typeof(MaxSpeed))
            {
                MaxSpeed = data as Dictionary<int, MaxSpeed>;
                return;
            }
            if (typeof(T) == typeof(Position))
            {
                Position = data as Dictionary<int, Position>;
                return;
            }
            if (typeof(T) == typeof(Radius))
            {
                Radius = data as Dictionary<int, Radius>;
                return;
            }
            if (typeof(T) == typeof(RandomSeed))
            {
                RandomSeed = data as Dictionary<int, RandomSeed>;
                return;
            }
            if (typeof(T) == typeof(RockId))
            {
                RockId = data as Dictionary<int, RockId>;
                return;
            }
            if (typeof(T) == typeof(Rotation))
            {
                Rotation = data as Dictionary<int, Rotation>;
                return;
            }
            if (typeof(T) == typeof(Separation))
            {
                Separation = data as Dictionary<int, Separation>;
                return;
            }
            if (typeof(T) == typeof(Separator))
            {
                Separator = data as Dictionary<int, Separator>;
                return;
            }
            if (typeof(T) == typeof(Squad))
            {
                Squad = data as Dictionary<int, Squad>;
                return;
            }
            if (typeof(T) == typeof(SquadMember))
            {
                SquadMember = data as Dictionary<int, SquadMember>;
                return;
            }
            if (typeof(T) == typeof(SyncId))
            {
                SyncId = data as Dictionary<int, SyncId>;
                return;
            }
            if (typeof(T) == typeof(SyncIdReserve))
            {
                SyncIdReserve = data as Dictionary<int, SyncIdReserve>;
                return;
            }
            if (typeof(T) == typeof(TargetSearchDistance))
            {
                TargetSearchDistance = data as Dictionary<int, TargetSearchDistance>;
                return;
            }
            if (typeof(T) == typeof(TeamId))
            {
                TeamId = data as Dictionary<int, TeamId>;
                return;
            }
            if (typeof(T) == typeof(TreeId))
            {
                TreeId = data as Dictionary<int, TreeId>;
                return;
            }
            if (typeof(T) == typeof(UnitId))
            {
                UnitId = data as Dictionary<int, UnitId>;
                return;
            }

            throw new NotSupportedException(typeof(T).Name);
        }
    }
}
